class FindingCause < Cause
  belongs_to :finding,foreign_key:"owner_id",class_name:"Finding"

  def self.get_headers
    [
      {:title => "Category",          :field => "category"},
      {:title => "Attribute",         :field => "get_attr"},
      {:title => "Value",             :field => "get_value"}
    ]
  end

  def get_value
    if self.value=="true"
      "Yes"
    else
      self.value
    end
  end

  def get_attr
    self.class.categories[self.category].each do |c|
      if c[:name]==self.send('attr')
        return c[:title].present? ? c[:title] : c[:name].titleize
      end
    end
  end

  def self.categories
    ({
      "Authority Issues" => [
        {name: "Conflicting", type: "check_box"},
        {name: "Inadequate", type: "check_box"},
        {name: "Ineffective", type: "check_box"},
        {name: "Non Existent", type: "check_box"},
        {name: "Not Documented", type: "check_box"},
        {name: "Not Known", type: "check_box"},
        {name: "Other", type: "text_field"},
      ],
      "Communication" => [
        {name: "Conflicting", type: "check_box"},
        {name: "Inadequate", type: "check_box"},
        {name: "Incorrect", type: "check_box"},
        {name: "Ineffective", type: "check_box"},
        {name: "Non Existent", type: "check_box"},
        {name: "Verbal", type: "check_box"},
        {name: "Written", type: "check_box"},
        {name: "Other", type: "text_field"},
      ],
      "Company Manuals" => [
        {name: "Company Manuals", type: "check_box"},
        {name: "Company Manuals-ATC", type: "check_box"},
        {name: "Customer Service Manual", type: "check_box"},
        {name: "Dispatch Manuals", type: "check_box"},
        {name: "Electronic Manual", type: "check_box"},
        {name: "Emergency Response Manual", type: "check_box"},
        {name: "FCOM/AOM", type: "check_box"},
        {name: "FOM", type: "check_box"},
        {name: "FSM", type: "check_box"},
        {name: "Ground Operations Manuals", type: "check_box"},
        {name: "IOM", type: "check_box"},
        {name: "MEL", type: "check_box"},
        {name: "MPPM", type: "check_box"},
        {name: "Quick Reference Handbook", type: "check_box"},
        {name: "Shipsets", type: "select", options: ["Not Revised","Incorrect Books","Incomplete"]},
        {name: "Other Company Manuals", type: "text_field"},
      ],
      "Contributing Factors" => [
        {name: "Awkward/Unsafe Position or Location", type: "check_box"},
        {name: "Improper/Inadequate Tooling", type: "check_box"},
        {name: "Inaccessible", type: "check_box"},
        {name: "Inadequate Training", type: "check_box"},
        {name: "Inappropriate for the Task", type: "check_box"},
        {name: "Incorrectly Labeled/Marked", type: "check_box"},
        {name: "Incorrectly Used", type: "check_box"},
        {name: "Malfunctions/Failure", type: "check_box"},
        {name: "No Instructions", type: "check_box"},
        {name: "Not Available or Broken", type: "check_box"},
        {name: "Not Guarded", type: "check_box"},
        {name: "Not Maintained", type: "check_box"},
        {name: "Not Properly Tagged/Locked", type: "check_box"},
        {name: "Not Understandable", type: "check_box"},
        {name: "Procedures not Effective/Adequate", type: "check_box"},
        {name: "Procedures not Enforced", type: "check_box"},
        {name: "Procedures not in Place", type: "check_box"},
        {name: "Procedures not used", type: "check_box"},
        {name: "Unreliable", type: "check_box"},
        {name: "Unsafe", type: "check_box"},
      ],
      "Control Issues" => [
        {name: "Inadequate", type: "check_box"},
        {name: "Ineffective", type: "check_box"},
        {name: "Non Existent", type: "check_box"},
        {name: "Not Documented", type: "check_box"},
        {name: "Not Followed", type: "check_box"},
        {name: "Other", type: "text_field"},
      ],
      "Documentation Error" => [
        {name: "Documentation Error", type: "check_box"},
        {name: "Closed in Error", type: "check_box"},
        {name: "Conflicting Maintenance Document", type: "check_box"},
        {name: "Confusing Software", type: "check_box"},
        {name: "Incorrect Paperwork/Log Book Entry", type: "check_box"},
        {name: "Incorrect Reference", type: "check_box"},
        {name: "Maintenance Not Scheduled", type: "check_box"},
        {name: "Missed Recertification/Downgrade", type: "check_box"},
        {name: "Missing Airworthiness Release", type: "check_box"},
        {name: "Missing Paperwork/Log Book Entry", type: "check_box"},
        {name: "Not Documented", type: "check_box"},
        {name: "Reference Data Not Used", type: "check_box"},
        {name: "Specifications", type: "check_box"},
        {name: "Work Card Error", type: "check_box"},
        {name: "Other Documentation Error", type: "text_field"},
      ],
      "Documentation/Information/Technical Data" => [
        {name: "Documentation/Information/Technical Data", type: "check_box"},
        {name: "AMM", type: "check_box"},
        {name: "Control of Documents", type: "check_box"},
        {name: "Control of Records", type: "check_box"},
        {name: "EO/EA", type: "check_box"},
        {name: "IPC", type: "check_box"},
        {name: "Inadequate Illustrations", type: "check_box"},
        {name: "Incorrect/Missing Documentation", type: "check_box"},
        {name: "Incorrect/Missing Release Final Weight and Balance", type: "check_box"},
        {name: "Incorrectly Modified Manufacturer's MM/SB", type: "check_box"},
        {name: "Information Not Used", type: "check_box"},
        {name: "Insufficient", type: "check_box"},
        {name: "Interpretation of Charts", type: "check_box"},
        {name: "Management of Flight Plan, Flight Release, Weather or NOTAMs", type: "check_box"},
        {name: "Management of HAZMAT Information", type: "check_box"},
        {name: "Management of Weight and Balance", type: "check_box"},
        {name: "Management or Interpretation of MEL/CDL", type: "check_box"},
        {name: "Management or Interpretation of Pre-Departure Clearance", type: "check_box"},
        {name: "N-R", type: "check_box"},
        {name: "Not Available/Inaccessible", type: "check_box"},
        {name: "Not Understandable", type: "check_box"},
        {name: "Operational Documentation", type: "check_box"},
        {name: "Reference Material Not Available", type: "check_box"},
        {name: "Reviewing, Recording or Departing with Wrong Logbook or Information", type: "check_box"},
        {name: "Too Much/Conflicting Information", type: "check_box"},
        {name: "Unclear Reference Material", type: "check_box"},
        {name: "Update Process is Too Long/Complicated", type: "check_box"},
        {name: "Other Documentation/Information/Technical Data", type: "text_field"},
      ],
      "Emergency Contingency Management" => [
        {name: "Execution", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
        {name: "Planning", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
        {name: "Preparation", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
      ],
      "Employee Issues" => [
        {name: "Employee Issues", type: "check_box"},
        {name: "Employee Conduct", type: "check_box"},
        {name: "Intoxicated", type: "check_box"},
        {name: "Other Employee Issues", type: "text_field"},
      ],
      "Facilities" => [
        {name: "Facilities", type: "check_box"},
        {name: "Access (Ladders, Stands)", type: "check_box"},
        {name: "Artificial Lighting: Fair", type: "check_box"},
        {name: "Artificial Lighting: Good", type: "check_box"},
        {name: "Artificial Lighting: Marginal", type: "check_box"},
        {name: "Artificial Lighting: None", type: "check_box"},
        {name: "Artificial Lighting: Poor", type: "check_box"},
        {name: "Cleanliness", type: "check_box"},
        {name: "Congested", type: "check_box"},
        {name: "HAZMAT/Toxic Substances", type: "check_box"},
        {name: "Inadequate Blast Protection", type: "check_box"},
        {name: "Not Adequate", type: "check_box"},
        {name: "Power Sources", type: "check_box"},
        {name: "Ramp Markings", type: "check_box"},
        {name: "Ventilation", type: "check_box"},
        {name: "Other Facilities", type: "text_field"},
      ],
      "Human Error" => [
        {name: "Human Error", type: "check_box"},
        {name: "Altitude Planning/Awareness", type: "check_box"},
        {name: "Disregard for Polices/Procedures", type: "check_box"},
        {name: "Improper Use of Autopilot/FMS/FMC/Nav Equipment", type: "check_box"},
        {name: "Maintenance Error (MEL, Oversight, MOC, Non-Compliance)", type: "check_box"},
        {name: "Misapplication of Flight Controls", type: "check_box"},
        {name: "Misapplication of Polices/Procedures", type: "check_box"},
        {name: "Misapplication of System Knowledge", type: "check_box"},
        {name: "Poor Performance Planning", type: "check_box"},
        {name: "Weight and Balance Error", type: "check_box"},
        {name: "Other Human Error", type: "text_field"},
      ],
      "Human Factors" => [
        {name: "Human Factors", type: "check_box"},
        {name: "Automation-FMS or Autopilot Usage", type: "check_box"},
        {name: "CRM", type: "select", options: ["Communication","Conflict Management","Incompatible Employee Pairing","Leadership and Command"]},
        {name: "DRM", type: "select", options: ["Communication","Conflict Management","Decisionmaking","Leadership and Command","Situational Awareness","**Team** **Building**","Workload Management","Other"]},
        {name: "Equipment Limitation", type: "check_box"},
        {name: "Equipment Placement", type: "check_box"},
        {name: "Ergonomics", type: "check_box"},
        {name: "Expectation Bias", type: "check_box"},
        {name: "Lack of Alertness", type: "check_box"},
        {name: "Pilot Handling-Judgment Airmanship", type: "check_box"},
        {name: "Poor Product Design", type: "check_box"},
        {name: "Two Heads Down", type: "check_box"},
        {name: "Unknown", type: "check_box"},
        {name: "User Interface", type: "check_box"},
        {name: "Other Human Factors", type: "text_field"},
      ],
      "Incorrect Procedure" => [
        {name: "Improper Procedure", type: "check_box"},
        {name: "Incomplete DDP", type: "check_box"},
        {name: "Missed Discrepancy", type: "check_box"},
        {name: "Procedure Not Followed", type: "check_box"},
        {name: "Procedures Not Workable", type: "check_box"},
        {name: "Skipped Procedure", type: "check_box"},
        {name: "Skipped Steps", type: "check_box"},
        {name: "Skipped Warning", type: "check_box"},
        {name: "Wrong Procedure Followed", type: "check_box"},
        {name: "Other Incorrect Procedure", type: "text_field"},
      ],
      "Individual Factors" => [
        {name: "Individual Factors", type: "check_box"},
        {name: "Alcohol Detected", type: "check_box"},
        {name: "Body Size/Strength", type: "check_box"},
        {name: "Circadian Cycle", type: "check_box"},
        {name: "Complacency", type: "check_box"},
        {name: "Crew Qualifications", type: "check_box"},
        {name: "Drug Detected", type: "check_box"},
        {name: "Environmental Stressors", type: "check_box"},
        {name: "Experience Level", type: "check_box"},
        {name: "Extended Duty/Commuting Periods", type: "check_box"},
        {name: "Fatigue", type: "check_box"},
        {name: "Fatigue/Lack of Alertness", type: "check_box"},
        {name: "Fear/Panic", type: "check_box"},
        {name: "High Workload/Task Saturation", type: "check_box"},
        {name: "Illness or Injury", type: "check_box"},
        {name: "Inadequate Training", type: "check_box"},
        {name: "Insufficient Attention to Detail", type: "check_box"},
        {name: "Interruption/Distraction", type: "check_box"},
        {name: "Lack of Alertness", type: "check_box"},
        {name: "Lack of Assertiveness", type: "check_box"},
        {name: "Lack of Motivation", type: "check_box"},
        {name: "Lack of Procedural Knowledge", type: "check_box"},
        {name: "Lack of Rest Periods", type: "check_box"},
        {name: "Lack of Situational Awareness", type: "check_box"},
        {name: "Medication Side Effect", type: "check_box"},
        {name: "Memory Lapse (Forgot)", type: "check_box"},
        {name: "Mental Health", type: "check_box"},
        {name: "Nutrition", type: "check_box"},
        {name: "On Time Performance Pressure", type: "check_box"},
        {name: "Operational Time Pressure, Delays, Push for On Time Performance", type: "check_box"},
        {name: "Peer Pressure", type: "check_box"},
        {name: "Perceptual Illusion/Spatial Disorientation", type: "check_box"},
        {name: "Personal Attitudes Toward Safety", type: "check_box"},
        {name: "Personal Event", type: "check_box"},
        {name: "Physical Health", type: "check_box"},
        {name: "Procedural-Checklists/Flows/Crosschecking", type: "check_box"},
        {name: "Proficiency/Over Reliance On Automation", type: "check_box"},
        {name: "Rotating Work Schedule", type: "check_box"},
        {name: "Self-Induced Time Pressure", type: "check_box"},
        {name: "Sleep Disruption", type: "check_box"},
        {name: "Sleep/Work Periods Conflict with Circadian Rhythms", type: "check_box"},
        {name: "Split-Shift", type: "check_box"},
        {name: "Stress", type: "check_box"},
        {name: "Syllabus/Schedule Pressure", type: "check_box"},
        {name: "Time Constraints", type: "check_box"},
        {name: "Unpredictable Work Schedules", type: "check_box"},
        {name: "Visual Perception", type: "check_box"},
        {name: "Workplace Distractions/Interruptions", type: "check_box"},
        {name: "Other Individual Factors", type: "text_field"},
      ],
      "Interface Issues" => [
        {name: "Inadequate", type: "check_box"},
        {name: "Ineffective", type: "check_box"},
        {name: "Non Existent", type: "check_box"},
        {name: "Not Documented", type: "check_box"},
        {name: "Not Followed", type: "check_box"},
        {name: "Other", type: "text_field"},
      ],
      "Leadership/Supervision Factors" => [
        {name: "Leadership/Supervision Factors", type: "check_box"},
        {name: "Amount of Supervision", type: "check_box"},
        {name: "Delegation/Assignment of Tasks", type: "check_box"},
        {name: "Does not Assure that Approved Process/Procedure is Followed", type: "check_box"},
        {name: "Lack of Leadership/Supervision", type: "check_box"},
        {name: "Planning/Organization of Tasks", type: "check_box"},
        {name: "Prioritization of Work", type: "check_box"},
        {name: "Unrealistic Attitude/Expectations", type: "check_box"},
        {name: "Other Leadership/Supervision Factors", type: "text_field"},
      ],
      "Maintenance Reference Material" => [
        {name: "Maintenance Reference Material", type: "check_box"},
        {name: "CDL No", type: "text_field"},
        {name: "Cabin Maintenance Log", type: "check_box"},
        {name: "MEL No", type: "text_field"},
        {name: "Notes", type: "check_box"},
        {name: "Procedures", type: "check_box"},
        {name: "Verbiage", type: "check_box"},
        {name: "Work Card", type: "check_box"},
        {name: "Other Maintenance Reference Material", type: "text_field"},
      ],
      "Narrative" => [
        {name: "Narrative", type: "text_area"},
      ],
      "Non-Compliance with CFRs, Policies/Procedures" => [
        {name: "Non-Compliance with CFRs, Policies/Procedures", type: "check_box"},
        {name: "Aircraft System SOPs", type: "check_box"},
        {name: "Airworthiness Directive", type: "check_box"},
        {name: "CFR Violation Part No", type: "text_field"},
        {name: "CFRs", type: "check_box"},
        {name: "Cabin Procedures", type: "check_box"},
        {name: "Carry on Baggage Limit", type: "check_box"},
        {name: "Checklist/Flows SOP Non-Compliance", type: "check_box"},
        {name: "Company Policy SOP Non-Compliance", type: "check_box"},
        {name: "Did Not Initialize Cabin Phone", type: "check_box"},
        {name: "Errors/Violations by Others", type: "check_box"},
        {name: "Exit Row/Moving Passenger Post Brief", type: "check_box"},
        {name: "Failure to Qualify", type: "select", options: ["Ineligible Lap Child Allowed","Jump Seat/JACS","Exit Row Seating"]},
        {name: "Flight/Duty Time Violation", type: "check_box"},
        {name: "HAZMAT Violation", type: "check_box"},
        {name: "Incorrect/Missing Manual Information", type: "check_box"},
        {name: "Infant Edit Not Completed", type: "check_box"},
        {name: "Non-Compliance-Clearance", type: "check_box"},
        {name: "Non-Compliance-Service Advisory", type: "check_box"},
        {name: "Preflight Check", type: "check_box"},
        {name: "Problem Enforcing CFRs", type: "check_box"},
        {name: "Published Procedure", type: "check_box"},
        {name: "Reduced Safety Standards", type: "check_box"},
        {name: "Reference", type: "text_field"},
        {name: "Regulatory Fine", type: "check_box"},
        {name: "Regulatory Violation", type: "check_box"},
        {name: "Required Legal Separation", type: "check_box"},
        {name: "Scheduling Rules", type: "check_box"},
        {name: "Smoking Ban Violation", type: "check_box"},
        {name: "Speed", type: "check_box"},
        {name: "Sterile Cockpit Violation", type: "check_box"},
        {name: "TSRs", type: "check_box"},
        {name: "Unaccompanied Minor", type: "check_box"},
        {name: "Weather Minimums", type: "check_box"},
        {name: "Other Cabin Non Compliance", type: "text_field"},
        {name: "Other Non-Compliance with CFRs, Policies/Procedures", type: "text_field"},
      ],
      "Organization Factors" => [
        {name: "Organizational Factors", type: "check_box"},
        {name: "Airline's Safety Culture", type: "check_box"},
        {name: "Company Policies", type: "check_box"},
        {name: "Corporate Change/Restructuring", type: "check_box"},
        {name: "Crew Selection", type: "check_box"},
        {name: "Employee Staffing", type: "check_box"},
        {name: "Failure to Follow Airport Authority Guidance", type: "check_box"},
        {name: "Failure to Follow Ground Guidance", type: "check_box"},
        {name: "Flight Safety Standardization", type: "check_box"},
        {name: "Improper Record Keeping Procedures", type: "check_box"},
        {name: "Inadequate Flight Management", type: "check_box"},
        {name: "Inadequate Ground Management", type: "check_box"},
        {name: "Inadequate Training", type: "check_box"},
        {name: "Labor Agreement", type: "check_box"},
        {name: "Lack of Accountability", type: "check_box"},
        {name: "Lack of Teamwork", type: "check_box"},
        {name: "Mismanagement of Assets", type: "check_box"},
        {name: "Not Enough Resources", type: "check_box"},
        {name: "Not Enough Staff", type: "check_box"},
        {name: "On Time Pressure", type: "check_box"},
        {name: "Quality of Support from Airport Organizations", type: "check_box"},
        {name: "Quality of Support from Airport Vendors", type: "check_box"},
        {name: "Quality of Support from Management", type: "check_box"},
        {name: "Reduced Safety Standards", type: "check_box"},
        {name: "Rest/Duty/Flight Time", type: "check_box"},
        {name: "Work Group Normal Practice (Norm)", type: "check_box"},
        {name: "Work Process/Procedure", type: "check_box"},
        {name: "Work Process/Procedure not Documented", type: "check_box"},
        {name: "Work Process/Procedure not Followed", type: "check_box"},
        {name: "Other Organizational Factors", type: "text_field"},
      ],
      "Policy Issues" => [
        {name: "Conflicting", type: "check_box"},
        {name: "Inadequate", type: "check_box"},
        {name: "Ineffective", type: "check_box"},
        {name: "Non Existent", type: "check_box"},
        {name: "Not Documented", type: "check_box"},
        {name: "Not Followed", type: "check_box"},
        {name: "Other", type: "text_field"},
      ],
      "Procedure Issues" => [
        {name: "Conflicting", type: "check_box"},
        {name: "Inadequate", type: "check_box"},
        {name: "Ineffective", type: "check_box"},
        {name: "Non Existent", type: "check_box"},
        {name: "Not Documented", type: "check_box"},
        {name: "Not Followed", type: "check_box"},
        {name: "Other", type: "text_field"},
      ],
      "Process Measurement Issues" => [
        {name: "Inadequate", type: "check_box"},
        {name: "Ineffective", type: "check_box"},
        {name: "Non Existent", type: "check_box"},
        {name: "Not Documented", type: "check_box"},
        {name: "Not Followed", type: "check_box"},
        {name: "Other", type: "text_field"},
      ],
      "Responsibility Issues" => [
        {name: "Conflicting", type: "check_box"},
        {name: "Inadequate", type: "check_box"},
        {name: "Ineffective", type: "check_box"},
        {name: "Non Existent", type: "check_box"},
        {name: "Not Documented", type: "check_box"},
        {name: "Other", type: "text_field"},
      ],
      "Root Cause" => [
        {name: "Primary Root Cause", type: "select", options: ["Communication - Non-standard turnover / turnover process not used","Procedure - Not developed","Procedure - Inadequate/need improvement","QC - Inspection instruction inadequate/not available","QC - Inspection techniques inadequate","Supervision/Management Systems - Supervisory Violation","Human Factors - Work Environment","Human Factors - Decision Based Error","Human Factors - Perceptual Error","Training - Needs improvement","Organizational Influences - Climate","Human Factors - Personnel Factors","Training - Did not exist/not implemented","Supervision/Management Systems - Failure to Correct Problem","Supervision/Management Systems - Management oversight needs improvement","Supervision/Management Systems - Corrective Actions ","QC - Inspection not required","Procedure - Followed incorrectly","Supervision/Management Systems - Inadequate Supervision","Human Factors - Skill-Based Error","Supervision/Management Systems - Planned Inappropriate Operation","Procedure - Not followed","Human Factors - Condition of Operation","Organizational Influences - Facility design needs improvement","Organizational Influences - Not funded","Communication - Not timely","Human Factors - Technological (Human Engineering)","Communication - Misunderstood verbal communications","Supervision/Management Systems - Standards, Policies or Admin Controls","Organizational Influences - Equip/Materials not properly maintained/needs improvement","Training - Did not understand training","Organizational Influences - Inadequate manpower/resource"]},
        {name: "Secondary Root Cause", type: "select", options: ["Communication - Non-standard turnover / turnover process not used","Procedure - Not developed","Procedure - Inadequate/need improvement","QC - Inspection instruction inadequate/not available","QC - Inspection techniques inadequate","Supervision/Management Systems - Supervisory Violation","Human Factors - Work Environment","Human Factors - Decision Based Error","Human Factors - Perceptual Error","Training - Needs improvement","Organizational Influences - Climate","Human Factors - Personnel Factors","Training - Did not exist/not implemented","Supervision/Management Systems - Failure to Correct Problem","Supervision/Management Systems - Management oversight needs improvement","Supervision/Management Systems - Corrective Actions ","QC - Inspection not required","Procedure - Followed incorrectly","Supervision/Management Systems - Inadequate Supervision","Human Factors - Skill-Based Error","Supervision/Management Systems - Planned Inappropriate Operation","Procedure - Not followed","Human Factors - Condition of Operation","Organizational Influences - Facility design needs improvement","Organizational Influences - Not funded","Communication - Not timely","Human Factors - Technological (Human Engineering)","Communication - Misunderstood verbal communications","Supervision/Management Systems - Standards, Policies or Admin Controls","Organizational Influences - Equip/Materials not properly maintained/needs improvement","Training - Did not understand training","Organizational Influences - Inadequate manpower/resource"]},
      ],
      "Station Operation Issues" => [
        {name: "Station Operation Issues", type: "check_box"},
        {name: "Access Panel Left Open", type: "check_box"},
        {name: "Air Start", type: "check_box"},
        {name: "Crew Hotel/Transportation", type: "check_box"},
        {name: "De-Icing", type: "check_box"},
        {name: "HAZMAT", type: "check_box"},
        {name: "Procedures", type: "check_box"},
        {name: "Remote Dispatch", type: "check_box"},
        {name: "Weather Resources", type: "check_box"},
        {name: "Other Station Operation Issues", type: "text_field"},
      ],
      "Station Ops Complications-Customer Service" => [
        {name: "Station Ops Complications-Customer Service", type: "check_box"},
        {name: "ADA", type: "check_box"},
        {name: "Agent  Availability", type: "check_box"},
        {name: "Agent closed boarding door", type: "check_box"},
        {name: "Aislechair", type: "check_box"},
        {name: "Baggage Claim", type: "check_box"},
        {name: "Baggage Non-Compliance Quantity", type: "check_box"},
        {name: "Baggage Non-Compliance Size", type: "check_box"},
        {name: "Board Room", type: "check_box"},
        {name: "Boarding", type: "check_box"},
        {name: "Deplanning", type: "check_box"},
        {name: "Gate Staff", type: "check_box"},
        {name: "Jetbridge Operations", type: "check_box"},
        {name: "Passenger Count Incorrect", type: "check_box"},
        {name: "Passenger Dissatisfied", type: "check_box"},
        {name: "Seat Assignment", type: "check_box"},
        {name: "Security", type: "check_box"},
        {name: "Station Appearance", type: "check_box"},
        {name: "Supplies", type: "check_box"},
        {name: "Ticketing", type: "check_box"},
        {name: "Unaccompanied Minor", type: "check_box"},
        {name: "Other Station Ops Complications-Customer Service", type: "text_field"},
      ],
      "Technical Data Error" => [
        {name: "Technical Data Error", type: "check_box"},
        {name: "Improper MEL/Deferral", type: "check_box"},
        {name: "Manuals", type: "check_box"},
        {name: "Reference Material", type: "check_box"},
        {name: "Work Cards", type: "check_box"},
        {name: "Other Technical Data", type: "text_field"},
      ],
      "Technical Knowledge/Skills" => [
        {name: "Technical Knowledge/Skills/Training", type: "check_box"},
        {name: "Aircraft Configuration Knowledge", type: "check_box"},
        {name: "Computing Skills", type: "check_box"},
        {name: "English Language Proficiency", type: "check_box"},
        {name: "Inadequate Aircraft System Knowledge", type: "check_box"},
        {name: "Inadequate Airline Process Knowledge", type: "check_box"},
        {name: "Inadequate Skills", type: "check_box"},
        {name: "Inadequate Task Experience", type: "check_box"},
        {name: "Inadequate Task Knowledge", type: "check_box"},
        {name: "Inadequate Task Planning", type: "check_box"},
        {name: "Teamwork Skills", type: "check_box"},
        {name: "Training Issues", type: "select", options: ["Incorrect","Lack of","No","Other","Yes"]},
        {name: "Training Situation", type: "select", options: ["Instructing","Other","Receiving Training"]},
        {name: "Other Technical Knowledge/Skills/Training", type: "text_field"},
      ],
      "Training: Central Load Planners" => [
        {name: "Dispatcher Training", type: "check_box"},
        {name: "Cockpit Jump Seat Observation", type: "check_box"},
        {name: "Communications", type: "check_box"},
        {name: "DRM Training", type: "check_box"},
        {name: "Decisionmaking", type: "check_box"},
        {name: "Deferred Items-MEL/CDL", type: "check_box"},
        {name: "Field Conditions", type: "check_box"},
        {name: "Flight Planning-Initial", type: "check_box"},
        {name: "Flight Releases", type: "check_box"},
        {name: "Initial", type: "check_box"},
        {name: "NOTAMs", type: "check_box"},
        {name: "Operational Control", type: "check_box"},
        {name: "Policies/Procedures", type: "check_box"},
        {name: "Recurrent", type: "check_box"},
        {name: "Other Dispatcher Training", type: "text_field"},
      ],
      "Training: Customer Service Representatives" => [
        {name: "Customer Service Representatives Training", type: "check_box"},
        {name: "Documentation", type: "check_box"},
        {name: "Passenger Carry Ons", type: "check_box"},
        {name: "Policies/Procedures", type: "check_box"},
        {name: "Security", type: "check_box"},
        {name: "Special Handling Passengers", type: "check_box"},
        {name: "Other Customer Service Representatives Training", type: "text_field"},
      ],
      "Training: Dispatchers" => [
        {name: "Dispatcher Training", type: "check_box"},
        {name: "Cockpit Jump Seat Observation", type: "check_box"},
        {name: "Communications", type: "check_box"},
        {name: "DRM Training", type: "check_box"},
        {name: "Decisionmaking", type: "check_box"},
        {name: "Deferred Items-MEL/CDL", type: "check_box"},
        {name: "Field Conditions", type: "check_box"},
        {name: "Flight Planning-Initial", type: "check_box"},
        {name: "Flight Releases", type: "check_box"},
        {name: "Initial", type: "check_box"},
        {name: "NOTAMs", type: "check_box"},
        {name: "Operational Control", type: "check_box"},
        {name: "Policies/Procedures", type: "check_box"},
        {name: "Recurrent", type: "check_box"},
        {name: "Other Dispatcher Training", type: "text_field"},
      ],
      "Training: Flight Attendants" => [
        {name: "Flight Attendants Training", type: "check_box"},
        {name: "Cabin Maintenance Log", type: "check_box"},
        {name: "Computer Based Training", type: "check_box"},
        {name: "Drills", type: "check_box"},
        {name: "Emergency Equipment", type: "check_box"},
        {name: "Initial", type: "check_box"},
        {name: "Life Support", type: "check_box"},
        {name: "Overwater", type: "check_box"},
        {name: "Policies/Procedures", type: "check_box"},
        {name: "Recurrent", type: "check_box"},
        {name: "Reports", type: "check_box"},
        {name: "Security", type: "check_box"},
        {name: "Other Flight Attendants Training", type: "text_field"},
      ],
      "Training: Ground Service Technicians" => [
        {name: "Ground Service Technicians Training", type: "check_box"},
        {name: "HAZMAT", type: "check_box"},
        {name: "Marshalling", type: "check_box"},
        {name: "Policies/Procedures", type: "check_box"},
        {name: "Pushback", type: "check_box"},
        {name: "Safety Zone", type: "check_box"},
        {name: "Security", type: "check_box"},
        {name: "Other Ground Service Technicians Training", type: "text_field"},
      ],
      "Training: Maintenance Technicians" => [
        {name: "Maintenance Technicians Training", type: "check_box"},
        {name: "APU Operations", type: "check_box"},
        {name: "Air Start", type: "check_box"},
        {name: "Policies/Procedures", type: "check_box"},
        {name: "Taxi/Tow Operations", type: "check_box"},
        {name: "Other Maintenance Technicians Training", type: "text_field"},
      ],
      "Training: Organization" => [
        {name: "Organization Training", type: "check_box"},
        {name: "Publish Article", type: "check_box"},
        {name: "Standardization", type: "check_box"},
        {name: "Supplement", type: "check_box"},
        {name: "Other Organization Training", type: "text_field"},
      ],
      "Training: Pilots" => [
        {name: "CRM", type: "check_box"},
        {name: "Computer Based Training", type: "check_box"},
        {name: "Emergency Equipment", type: "check_box"},
        {name: "Flight Deck Procedures", type: "check_box"},
        {name: "General Operating Systems", type: "check_box"},
        {name: "Home Study", type: "check_box"},
        {name: "Initial Indoctrination/Awareness", type: "check_box"},
        {name: "MEL", type: "check_box"},
        {name: "Overwater", type: "check_box"},
        {name: "Pilot Training", type: "check_box"},
        {name: "Policies/Procedures", type: "check_box"},
        {name: "Recurrent", type: "check_box"},
        {name: "SPT", type: "check_box"},
        {name: "Simulator PC", type: "check_box"},
        {name: "Simulator PT", type: "check_box"},
        {name: "Standardization", type: "check_box"},
        {name: "Systems Airbus", type: "select", options: ["A300","A310","A319","A320","A321","A330","Other"]},
        {name: "Systems Boeing", type: "select", options: ["B717","B727","B737-100/200","B737-300/400/500","B737-NG","B747","B757","B767","B777","Other"]},
        {name: "Systems Embraer", type: "select", options: ["EMB-120","EMB-135","EMB-140","EMB-145","EMB-XRJ","Other"]},
        {name: "Transition", type: "check_box"},
        {name: "Upgrade", type: "check_box"},
        {name: "Other Pilot Training", type: "text_field"},
      ],
      "Weight and Balance Event" => [
        {name: "Weight and Balance", type: "check_box"},
        {name: "Actual Center of Gravity", type: "text_field"},
        {name: "Actual Load Did Not Match Inbound Load Message", type: "check_box"},
        {name: "Actual Weight", type: "text_field"},
        {name: "Aircraft Loaded Weight/CG Error", type: "check_box"},
        {name: "Aircraft Loaded Weight/CG Error", type: "select", options: ["Incorrect Bag Count","Incorrect Freight Weight","Other"]},
        {name: "CG Difference", type: "text_field"},
        {name: "CG from Datum", type: "check_box"},
        {name: "CG from Nose", type: "check_box"},
        {name: "CLP Contacted", type: "check_box"},
        {name: "Calculation Error", type: "check_box"},
        {name: "Cargo", type: "select", options: ["Restrained","Other","Shifting"]},
        {name: "Cargo Loading Error", type: "check_box"},
        {name: "Cargo Shift", type: "check_box"},
        {name: "Cargo/Bag Documentation Error", type: "select", options: ["Undocumented Cargo Loaded","Documented Cargo Not Loaded","Undocumented Bag Loaded","Documented Bag Not Loaded","Items Not in Documented PIT","Other Count/Weight Error"]},
        {name: "Center of Gravity", type: "check_box"},
        {name: "Center of Gravity Error Type", type: "select", options: ["Cargo/Bags in Wrong Location","Igloos/Cargo Containers in Wrong Location"]},
        {name: "Exceeded CG limitations", type: "check_box"},
        {name: "Exceeded PIT/ULD limitations", type: "check_box"},
        {name: "Exceeded running load restrictions", type: "check_box"},
        {name: "Incorrect Planning Tool Used", type: "check_box"},
        {name: "Input Error", type: "check_box"},
        {name: "Items not in Documented Pit", type: "check_box"},
        {name: "Load Verification Error", type: "check_box"},
        {name: "MTOW Exceeded", type: "check_box"},
        {name: "Maximum Landing Weight (lbs)", type: "text_field"},
        {name: "Maximum Takeoff Weight (lbs)", type: "text_field"},
        {name: "Maximum Taxi Weight (lbs)", type: "text_field"},
        {name: "Maximum Zero Fuel Weight (lbs)", type: "text_field"},
        {name: "Over Max Zero Fuel Weight", type: "check_box"},
        {name: "Over Release Weight", type: "check_box"},
        {name: "Overweight Takeoff", type: "check_box"},
        {name: "Overweight Taxi", type: "check_box"},
        {name: "Overweight for Ground Surface Limits", type: "check_box"},
        {name: "Passenger Loading/Count Error", type: "check_box"},
        {name: "Passenger Loading/Count Error Type", type: "select", options: ["Incorrect Count","Zone Distribution Error","Jump Seat Error"]},
        {name: "Payload>10,000 Kgs", type: "check_box"},
        {name: "Reported Center of Gravity", type: "text_field"},
        {name: "Reported Weight", type: "text_field"},
        {name: "Reported ZFW", type: "check_box"},
        {name: "Shelf Weight Exceedence", type: "check_box"},
        {name: "Center of Gravity Location at Time of Accident/Incident in Inches", type: "text_field"},
        {name: "Percent Mean Aerodynamic Cord (%MAC)", type: "text_field"},
        {name: "Actual ZFW", type: "text_field"},
        {name: "Other Weight and Balance Event", type: "text_field"},
        {name: "Reported ZFW", type: "text_field"},
        {name: "Weight Difference", type: "text_field"},
      ],
    }).sort.to_h
  end

end
