class Cause < ActiveRecord::Base


  def self.get_meta_fields(*args)
    visible_fields = (args.empty? ? ['index', 'form', 'show'] : args)
    return [
      {:field => "id",                :title => "ID",           :num_cols => 4,   :type => "text",        :visible => 'index',  :required => false},
      {                                                                           :type => "newline",     :visible => 'form'},
      {:field => "category",          :title => "Category",                       :type => "text",        :visible => 'form,show'},
      {:field => "get_attr",          :title => "Attribute",                      :type => "text",        :visible => 'form,show'},
      {:field => "get_value",         :title => "Value",                          :type => "text",        :visible => 'form,show'}
    ].select{|f| (f[:visible].split(',') & visible_fields).any?}
  end

  def get_attr
    Rails.logger.debug "cause get attr"
    derived_type = Object.const_get(type)
    if derived_type.categories.include?(self.category)
      derived_type.categories[self.category].each do |c|
        if c[:name]==self.send('attr')
          return c[:title].present? ? c[:title] : c[:name].titleize
        end
      end
    end
    return self.send("attr")
  end

  def self.categories
    {
      'Authority Issues'=> [
        {:name=>"conflicting",:type=>"check_box"},
        {:name=>"inadequate",:type=>"check_box"},
        {:name=>"ineffective",:type=>"check_box"},
        {:name=>"non_existent",:type=>"check_box"},
        {:name=>"not_documented",:type=>"check_box"},
        {:name=>"not_known",:type=>"check_box"},
        {:name=>"other",:type=>"text_field"}
      ],
      'Communication'=> [
        {:name=>"conflicting",:type=>"check_box"},
        {:name=>"inadequate",:type=>"check_box"},
        {:name=>"incorrect",:type=>"check_box"},
        {:name=>"ineffective",:type=>"check_box"},
        {:name=>"non_existent",:type=>"check_box"},
        {:name=>"verbal",:type=>"check_box"},
        {:name=>"written",:type=>"check_box"},
        {:name=>"other",:type=>"text_field"}
      ],
      'Company Manuals'=> [
        {:name=>"company_manuals",:type=>"check_box"},
        {:name=>"amros_procedure/function",:title=>"AMROS Procedure/Function",:type=>"check_box"},
        {:name=>"company_manuals-atc",:title=>"Company Manuals-ATC",:type=>"check_box"},
        {:name=>"customer_service_manuals",:type=>"check_box"},
        {:name=>"dispatch_manuals",:type=>"check_box"},
        {:name=>"electronic_manuals",:type=>"check_box"},
        {:name=>"emergency_response_manual",:type=>"check_box"},
        {:name=>"fcom/aom",:title=>"FOCM/AOM",:type=>"check_box"},
        {:name=>"fom",:title=>"FOM",:type=>"check_box"},
        {:name=>"fsm",:title=>"FSM",:type=>"check_box"},
        {:name=>"ground_operations_manuals",:type=>"check_box"},
        {:name=>"iom",:title=>"IOM",:type=>"check_box"},
        {:name=>"mel",:title=>"MEL",:type=>"check_box"},
        {:name=>"mppm",:title=>"MPPM",:type=>"check_box"},
        {:name=>"materials_dept._procedures",:type=>"check_box"},
        {:name=>"planning_procedure",:type=>"check_box"},
        {:name=>"production_control_procedures",:type=>"check_box"},
        {:name=>"quality_control_procedures",:type=>"check_box"},
        {:name=>"quick_reference_handbook",:type=>"check_box"},
        {:name=>"repair_station_manual",:type=>"check_box"},
        {:name=>"safety_mgmt._system_manual",:type=>"check_box"},
        {:name=>"shipsets",:type=>"select",:options=>['Not Revised','Incorrect Books','Incomplete']},
        {:name=>"training_department_manual",:type=>"check_box"},
        {:name=>"other_company_manuals",:type=>"text_field"}
      ],
      'Contributing Factors'=> [
        {:name=>"awkward/unsafe_positioning_or_location",:title=>"Awkward/Unsafe Position or Location",:type=>"check_box"},
        {:name=>"improper/inadequate_tooling",:type=>"check_box"},
        {:name=>"inaccessible",:type=>"check_box"},
        {:name=>"inadequate_training",:type=>"check_box"},
        {:name=>"inappropriate_for_the_task",:title=>"Inappropriate for the Task",:type=>"check_box"},
        {:name=>"incorrectly_labeled/marked",:type=>"check_box"},
        {:name=>"incorrectly_used",:type=>"check_box"},
        {:name=>"malfunction/failure",:type=>"check_box"},
        {:name=>"no_instructions",:type=>"check_box"},
        {:name=>"not_available_or_broken",:title=>"Not Available or Broken",:type=>"check_box"},
        {:name=>"not_guarded",:type=>"check_box"},
        {:name=>"not_maintained",:type=>"check_box"},
        {:name=>"not_properly_tagged/locked",:type=>"check_box"},
        {:name=>"not_understandable",:type=>"check_box"},
        {:name=>"procedures_not_effective/adequate",:title=>"Procedures not Effective/Adequate",:type=>"check_box"},
        {:name=>"procedures_not_enforced",:title=>"Procedures not Enforced",:type=>"check_box"},
        {:name=>"procedures_not_in_place",:title=>"Procedures not in Place",:type=>"check_box"},
        {:name=>"procedures_not_used",:title=>"Procedures not used",:type=>"check_box"},
        {:name=>"unreliable",:type=>"check_box"},
        {:name=>"unsafe",:type=>"check_box"}
      ],
      'Control Issues'=> [
        {:name=>"inadequate",:type=>"check_box"},
        {:name=>"ineffective",:type=>"check_box"},
        {:name=>"non_existent",:type=>"check_box"},
        {:name=>"not_documented",:type=>"check_box"},
        {:name=>"not_followed",:type=>"check_box"},
        {:name=>"other",:type=>"text_field"}
      ],
      'Documentation Error'=> [
        {:name=>"documentation_error",:type=>"check_box"},
        {:name=>"closed_in_error",:title=>"Closed in Error",:type=>"check_box"},
        {:name=>"conflicting_maintenance_document",:type=>"check_box"},
        {:name=>"confusing_software",:type=>"check_box"},
        {:name=>"incorrect_paperwork/log_book_entry",:type=>"check_box"},
        {:name=>"incorrect_reference",:type=>"check_box"},
        {:name=>"maintenance_not_scheduled",:type=>"check_box"},
        {:name=>"missed_recertification/downgrade",:type=>"check_box"},
        {:name=>"missing_airworthiness_release",:type=>"check_box"},
        {:name=>"missing_paperwork/log_book_entry",:type=>"check_box"},
        {:name=>"not_documented",:type=>"check_box"},
        {:name=>"reference_data_not_used",:type=>"check_box"},
        {:name=>"specifications",:type=>"check_box"},
        {:name=>"work_card_error",:type=>"check_box"},
        {:name=>"other_documentation_error",:type=>"text_field"}
      ],
      'Documentation/Information/Technical Data Attributes'=> [
        {:name=>"documentation/information/technical_data",:type=>"check_box"},
        {:name=>"amm",:title=>"AMM",:type=>"check_box"},
        {:name=>"control_of_documents",:title=>"Control of Documents",:type=>"check_box"},
        {:name=>"control_of_records",:title=>"Control of Records",:type=>"check_box"},
        {:name=>"eo/ea",:title=>"EO/EA",:type=>"check_box"},
        {:name=>"ipc",:title=>"IPC",:type=>"check_box"},
        {:name=>"inadequate_illustrations",:type=>"check_box"},
        {:name=>"incorrect/missing_documentation",:type=>"check_box"},
        {:name=>"incorrect/missing_release_final_weight_and_balance",:title=>"Incorrect/Missing Release Final Weight and Balance",:type=>"check_box"},
        {:name=>"incorrectly_modified_manufactur's_mm/sb",:title=>"Incorrectly Modified Manufacturer's MM/SB",:type=>"check_box"},
        {:name=>"information_not_used",:type=>"check_box"},
        {:name=>"insufficent",:type=>"check_box"},
        {:name=>"interpretation_of_charts",:title=>"Interpretation of Charts",:type=>"check_box"},
        {:name=>"management_of_flight_plan,_flight_release,_weather_or_notams",:title=>"Management of Flight Plan, Flight Release, Weather or NOTAMs",:type=>"check_box"},
        {:name=>"management_of_hazmat_information",:title=>"Management of HAZMAT Information",:type=>"check_box"},
        {:name=>"management_of_weight_and_balance",:title=>"Management of Weight and Balance",:type=>"check_box"},
        {:name=>"management_or_interpretation_of_mel/cdl",:title=>"Management or Interpretation of MEL/CDL",:type=>"check_box"},
        {:name=>"management_or_interpretation_of_pre-departure_clearance",:title=>"Management or Interpretation of Pre-Departure Clearance",:type=>"check_box"},
        {:name=>"n-r",:title=>"N-R",:type=>"check_box"},
        {:name=>"not_available/inaccessible",:type=>"check_box"},
        {:name=>"not_understandable",:type=>"check_box"},
        {:name=>"operational_documentation",:type=>"check_box"},
        {:name=>"reference_material_not_available",:type=>"check_box"},
        {:name=>"reviewing,_recording_or_departing_with_wrong_logbook_or_information",:title=>"Reviewing, Recording or Departing with Wrong Logbook or Information",:type=>"check_box"},
        {:name=>"too_much/conflicting_information",:type=>"check_box"},
        {:name=>"unclear_reference_material",:type=>"check_box"},
        {:name=>"update_process_is_too_long/complicated",:title=>"Update Process is Too Long/Complicated",:type=>"check_box"},
        {:name=>"other_documentation/information/technical_data",:type=>"text_field"}
      ],
      'Emergency Contigency Management'=> [
        {:name=>"execution",:type=>"select",:options=>['Inadequate','Ineffective','Non-Existent','Not Documented','Not Followed']},
        {:name=>"planning",:type=>"select",:options=>['Inadequate','Ineffective','Non-Existent','Not Documented','Not Followed']},
        {:name=>"preparation",:type=>"select",:options=>['Inadequate','Ineffective','Non-Existent','Not Documented','Not Followed']}
        ],
      'Employee Issues'=> [
        {:name=>"employee_issues",:type=>"check_box"},
        {:name=>"employee_conduct",:type=>"check_box"},
        {:name=>"intoxicated",:type=>"check_box"},
        {:name=>"other_employee_issues",:type=>"text_field"}
      ],
      'Facilities'=> [
        {:name=>"facilities",:type=>"check_box"},
        {:name=>"access_(ladders,_stands)",:type=>"check_box"},
        {:name=>"aircraft_lock-out/tag/out",:title=>"Aircraft Lock-Out/Tag-Out",:type=>"check_box"},
        {:name=>"artificial_lighting:_fair",:type=>"check_box"},
        {:name=>"artificial_lighting:_good",:type=>"check_box"},
        {:name=>"artificial_lighting:_marginal",:type=>"check_box"},
        {:name=>"artificial_lighting:_none",:type=>"check_box"},
        {:name=>"artificial_lighting:_poor",:type=>"check_box"},
        {:name=>"cleanliness",:type=>"check_box"},
        {:name=>"compressed_gases",:type=>"check_box"},
        {:name=>"congested",:type=>"check_box"},
        {:name=>"electrical_safety",:type=>"check_box"},
        {:name=>"non_existent",:type=>"check_box"},
        {:name=>"emergency_response_plan",:type=>"check_box"},
        {:name=>"facility_lock-out/tag/out",:title=>"Facility Lock-Out/Tag-Out",:type=>"check_box"},
        {:name=>"facility_maintenance",:type=>"check_box"},
        {:name=>"hazmat/toxic_substances",:title=>"HAZMAT/Toxic Substances",:type=>"check_box"},
        {:name=>"hoists/slings",:type=>"check_box"},
        {:name=>"inadequate_blast_protection",:type=>"check_box"},
        {:name=>"machine_guards",:type=>"check_box"},
        {:name=>"not_adequate",:type=>"check_box"},
        {:name=>"power_sources",:type=>"check_box"},
        {:name=>"ramp_markings",:type=>"check_box"},
        {:name=>"ventilation",:type=>"check_box"},
        {:name=>"other_facilities",:type=>"text_field"}
        ],
      'Human Error'=> [
        {:name=>"human_error",:type=>"check_box"},
        {:name=>"altitude_planning_awareness",:type=>"check_box"},
        {:name=>"disregard_for_policies/planning",:title=>"Disregard for Polices/Procedures",:type=>"check_box"},
        {:name=>"improper_use_of_autopilot/fms/nav_equipment",:title=>"Improper Use of Autopilot/FMS/FMC/Nav Equipment",:type=>"check_box"},
        {:name=>"maintenance_error_(mel,_oversight,_moc,_non-compliance",:title=>"Maintenance Error (MEL, Oversight, MOC, Non-Compliance)",:type=>"check_box"},
        {:name=>"missaplication_of_flight_controls",:title=>"Misapplication of Flight Controls",:type=>"check_box"},
        {:name=>"missaplication_of_policies/procedures",:title=>"Misapplication of Polices/Procedures",:type=>"check_box"},
        {:name=>"missaplication_of_system_knowledge",:title=>"Misapplication of System Knowledge",:type=>"check_box"},
        {:name=>"poor_performance_planning",:type=>"check_box"},
        {:name=>"weight_and_balance_error",:title=>"Weight and Balance Error",:type=>"check_box"},
        {:name=>"other_human_error",:type=>"text_field"}
      ],
      'Human Factors'=> [
        {:name=>"human_factors",:type=>"check_box"},
        {:name=>"automation-fms_or_autopilot_usage",:title=>"Automation-FMS or Autopilot Usage",:type=>"check_box"},
        {:name=>"crm",:title=>"CRM",:type=>"check_box"},
        {:name=>"crm",:title=>"CRM",:type=>"select",:options=>['Communication','Conflict Management','Incompatible Employee Pairing','Leadership and Command']},
        {:name=>"drm",:title=>"DRM",:type=>"select",:options=>['Communication','Conflict Management','Incompatible Employee Pairing','Decisionmaking','Leadership and Command','Situational Awareness','**Team** **Building**','Workload Management','Other']},
        {:name=>"equipment_limitation",:type=>"check_box"},
        {:name=>"equipment_placement",:type=>"check_box"},
        {:name=>"ergonomics",:type=>"check_box"},
        {:name=>"expectation_bias",:type=>"check_box"},
        {:name=>"lack_of_alertness",:title=>"Lack of Alertness",:type=>"check_box"},
        {:name=>"pilot_handling_judgment_airmanship",:title=>"Pilot Handling-Judgment Airmanship",:type=>"check_box"},
        {:name=>"poor_product_design",:type=>"check_box"},
        {:name=>"request_to_deviate_from_sops",:title=>"Requested to deviate from SOPs",:type=>"check_box"},
        {:name=>"two_heads_down",:type=>"check_box"},
        {:name=>"unknown",:type=>"check_box"},
        {:name=>"user_interface",:type=>"check_box"},
        {:name=>"aircrew_error",:type=>"select",:options=>['Flight Handling Error','Procedural Error','Communication Error', 'Decision Error']},
        {:name=>"other_human_factors",:type=>"text_field"}
      ],
      'Incorrect Procedure'=> [
        {:name=>"improper_procedure",:type=>"check_box"},
        {:name=>"incomplete_ddp",:title=>"Incomplete DDP",:type=>"check_box"},
        {:name=>"missed_discrepancey",:type=>"check_box"},
        {:name=>"procedure_not_followed",:type=>"check_box"},
        {:name=>"procedures_not_workable",:type=>"check_box"},
        {:name=>"skipped_procedure",:type=>"check_box"},
        {:name=>"skipped_steps",:type=>"check_box"},
        {:name=>"skipped_warning",:type=>"check_box"},
        {:name=>"wrong_procedure_followed",:type=>"check_box"},
        {:name=>"other_incorrect_procedure",:type=>"text_field"}
      ],
      'Individual Factors'=> [
        {:name=>"individual_factors",:type=>"check_box"},
        {:name=>"alcohol_detected",:type=>"check_box"},
        {:name=>"body_size/strength",:type=>"check_box"},
        {:name=>"circadian_cycle",:type=>"check_box"},
        {:name=>"complacency",:type=>"check_box"},
        {:name=>"crew_qualification",:type=>"check_box"},
        {:name=>"drug_detected",:type=>"check_box"},
        {:name=>"environmental_stressors",:type=>"check_box"},
        {:name=>"experienced_level",:type=>"check_box"},
        {:name=>"extended_duty/commuting_periods",:type=>"check_box"},
        {:name=>"fatigue",:type=>"check_box"},
        {:name=>"fatigue/lack_of_alertness",:type=>"check_box"},
        {:name=>"fear/panic",:type=>"check_box"},
        {:name=>"high_workload/task_saturation",:type=>"check_box"},
        {:name=>"illness_or_injury",:title=>"Illness or Injury",:type=>"check_box"},
        {:name=>"inadequate_training",:type=>"check_box"},
        {:name=>"insufficent_attention_to_detail",:title=>"Insufficient Attention to Detail",:type=>"check_box"},
        {:name=>"interruption/distraction",:type=>"check_box"},
        {:name=>"lack_of_alertness",:title=>"Lack of Alertness",:type=>"check_box"},
        {:name=>"lack_of_assertiveness",:title=>"Lack of Assertiveness",:type=>"check_box"},
        {:name=>"lack_of_motivation",:title=>"Lack of Motivation",:type=>"check_box"},
        {:name=>"lack_of_procedural_knowledge",:title=>"Lack of Procedural Knowledge",:type=>"check_box"},
        {:name=>"lack_of_rest_periods",:title=>"Lack of Rest Periods",:type=>"check_box"},
        {:name=>"lack_of_situational_awareness",:title=>"Lack of Situational Awareness",:type=>"check_box"},
        {:name=>"medication_side_effect",:type=>"check_box"},
        {:name=>"memory_lapse_(forgot)",:type=>"check_box"},
        {:name=>"mental_health",:type=>"check_box"},
        {:name=>"nutrition",:type=>"check_box"},
        {:name=>"on_time_performance_pressure",:type=>"check_box"},
        {:name=>"operational_time_pressure,_delays,_push_for_on_time_performance",:title=>"Operational Time Pressure, Delays, Push for On Time Performance",:type=>"check_box"},
        {:name=>"peer_pressure",:type=>"check_box"},
        {:name=>"perceptual_illusion/spatial_disorientation",:type=>"check_box"},
        {:name=>"personal_attitudes_toward_safety",:type=>"check_box"},
        {:name=>"personal_event",:type=>"check_box"},
        {:name=>"physical_health",:type=>"check_box"},
        {:name=>"procedural-checklists/flows/crosschecking",:title=>"Procedural-Checklists/Flows/Crosschecking",:type=>"check_box"},
        {:name=>"proficiency/over_reliance_on_automation",:type=>"check_box"},
        {:name=>"rotationg_work_schedule",:type=>"check_box"},
        {:name=>"self-induced_time_pressure",:title=>"Self-Induced Time Pressure",:type=>"check_box"},
        {:name=>"sleep_disruption",:type=>"check_box"},
        {:name=>"sleep/work_perods_conflict-with_circadian_rhythms",:title=>"Sleep/Work Periods Conflict with Circadian Rhythms",:type=>"check_box"},
        {:name=>"split-shift",:title=>"Split-Shift",:type=>"check_box"},
        {:name=>"stress",:type=>"check_box"},
        {:name=>"syllabus/schedule_pressure",:type=>"check_box"},
        {:name=>"time_constraints",:type=>"check_box"},
        {:name=>"unpredictable_work_schedules",:type=>"check_box"},
        {:name=>"visual_perception",:type=>"check_box"},
        {:name=>"workplace_distractions/interruptions",:type=>"check_box"},
        {:name=>"other_individual_factors",:type=>"text_field"}
      ],
      'Interface Issues'=> [
        {:name=>"inadequate",:type=>"check_box"},
        {:name=>"ineffective",:type=>"check_box"},
        {:name=>"non_existent",:type=>"check_box"},
        {:name=>"not_documented",:type=>"check_box"},
        {:name=>"not_followed",:type=>"check_box"},
        {:name=>"other",:type=>"text_field"}
      ],
      'Leadership/Supervision Factors'=> [
        {:name=>"leadership/supervision_factors",:type=>"check_box"},
        {:name=>"amount_of_supervision",:title=>"Amount of Supervision",:type=>"check_box"},
        {:name=>"delegation/assignment_of_tasks",:title=>"Delegation/Assignment of Tasks",:type=>"check_box"},
        {:name=>"does_not_assure_tat_approved_process/procedure_is_followed",:title=>"Does not Assure that Approved Process/Procedure is Followed",:type=>"check_box"},
        {:name=>"lack_of_leadership/supervision",:title=>"Lack of Leadership/Supervision",:type=>"check_box"},
        {:name=>"planning_organization_of_tasks",:title=>"Planning/Organization of Tasks",:type=>"check_box"},
        {:name=>"prioritization_of_work",:title=>"Prioritization of Work",:type=>"check_box"},
        {:name=>"unrealistic_attitude/expectations",:type=>"check_box"},
        {:name=>"other_leadership/supervision_factors",:type=>"text_field"}
      ],
      'Maintenance Reference Material'=> [
        {:name=>"maintenance_reference_material",:type=>"check_box"},
        {:name=>"cdl_no",:title=>"CDL No",:type=>"text_field"},
        {:name=>"cabin_maintenance_log",:type=>"check_box"},
        {:name=>"mel_no",:title=>"MEL No",:type=>"text_field"},
        {:name=>"notes",:type=>"check_box"},
        {:name=>"procedures",:type=>"check_box"},
        {:name=>"verbiage",:type=>"check_box"},
        {:name=>"work_card",:type=>"check_box"},
        {:name=>"other_maintenance_reference_material",:type=>"text_field"}
      ],
      'Narrative'=> [
        {:name=>"narrative",:type=>"text_area"}
      ],
      'Non-Compliance with CFRs,Policies/Procedures Attributes'=> [
        {:name=>"non-compliance_with_cfrs,_policies/procedures",:title=>"Non-Compliance with CFRs, Policies/Procedures",:type=>"check_box"},
        {:name=>"aircraft_systems_sops",:title=>"Aircraft System SOPs",:type=>"check_box"},
        {:name=>"airworthiness_directive",:type=>"check_box"},
        {:name=>"cfr_violations_part_no",:title=>"CFR Violation Part No",:type=>"text_field"},
        {:name=>"cfrs",:title=>"CFRs",:type=>"check_box"},
        {:name=>"cabin_procedures",:type=>"check_box"},
        {:name=>"carry_on_baggage_limit",:title=>"Carry on Baggage Limit",:type=>"check_box"},
        {:name=>"checklist/flows_sop_non-compliance",:title=>"Checklist/Flows SOP Non-Compliance",:type=>"check_box"},
        {:name=>"company_policy_sop_non-compliance",:title=>"Company Policy SOP Non-Compliance",:type=>"check_box"},
        {:name=>"did_not_initialize_cabin_phone",:type=>"check_box"},
        {:name=>"errors/violations_by_others",:title=>"Errors/Violations by Others",:type=>"check_box"},
        {:name=>"exit_row/moving_passenger_post_brief",:type=>"check_box"},
        {:name=>"failure_to_qualify",:title=>"Failure to Qualify",:type=>"select",:options=>['Ineligible Lap Child Allowed','Jump Seat/JACS','Exit Row Seating']},
        {:name=>"flight/duty_time_violation",:type=>"check_box"},
        {:name=>"hazmat_violation",:title=>"HAZMAT Violation",:type=>"check_box"},
        {:name=>"incorrect/missing_manual_information",:type=>"check_box"},
        {:name=>"infant_edit_not_completed",:type=>"check_box"},
        {:name=>"non-compliance-clearance",:title=>"Non-Compliance-Clearance",:type=>"check_box"},
        {:name=>"non-compliance-service_advisory",:title=>"Non-Compliance-Service Advisory",:type=>"check_box"},
        {:name=>"preflight_check",:type=>"check_box"},
        {:name=>"problem_enforcing_cfrs",:title=>"Problem Enforcing CFRs",:type=>"check_box"},
        {:name=>"published_procedure",:type=>"check_box"},
        {:name=>"reduced_safety_standards",:type=>"check_box"},
        {:name=>"reference",:type=>"text_field"},
        {:name=>"regulatory_fine",:type=>"check_box"},
        {:name=>"regulatory_violation",:type=>"check_box"},
        {:name=>"required_legal_separation",:type=>"check_box"},
        {:name=>"scheduling_rules",:type=>"check_box"},
        {:name=>"smoking_ban_violaton",:type=>"check_box"},
        {:name=>"speed",:type=>"check_box"},
        {:name=>"sterile_cockpit_violation",:type=>"check_box"},
        {:name=>"tsrs",:title=>"TSRs",:type=>"check_box"},
        {:name=>"unaccompanied_minor",:type=>"check_box"},
        {:name=>"weather_minimums",:type=>"check_box"},
        {:name=>"other_cabin_non_compliance",:type=>"text_field"},
        {:name=>"other_non-compliance_with_cfrs,_policies/procedures",:title=>"Other Non-Compliance with CFRs, Policies/Procedures",:type=>"text_field"}
      ],
      'Organization Factors'=> [
        {:name=>"organizational_factors",:type=>"check_box"},
        {:name=>"airline's_safety_culture",:type=>"check_box"},
        {:name=>"company_policies",:type=>"check_box"},
        {:name=>"corporate_change/restructuring",:type=>"check_box"},
        {:name=>"crew_selection",:type=>"check_box"},
        {:name=>"employee_staffing",:type=>"check_box"},
        {:name=>"failure_to_follow_airport_authority_guidance",:title=>"Failure to Follow Airport Authority Guidance",:type=>"check_box"},
        {:name=>"failure_to_follow_ground_guidance",:title=>"Failure to Follow Ground Guidance",:type=>"check_box"},
        {:name=>"flight_safety_standardizaton",:type=>"check_box"},
        {:name=>"improper_record_keeping_procedures",:type=>"check_box"},
        {:name=>"inadequate_flight_management",:type=>"check_box"},
        {:name=>"inadequate_ground_management",:type=>"check_box"},
        {:name=>"inadequate_training",:type=>"check_box"},
        {:name=>"labor_agreement",:type=>"check_box"},
        {:name=>"lack_of_agreement",:title=>"Lack of Accountability",:type=>"check_box"},
        {:name=>"lack_of_teamwork",:title=>"Lack of Teamwork",:type=>"check_box"},
        {:name=>"mismanagement_of_assets",:title=>"Mismanagement of Assets",:type=>"check_box"},
        {:name=>"not_enough_resources",:type=>"check_box"},
        {:name=>"not_enough_staff",:type=>"check_box"},
        {:name=>"on_time_pressure",:type=>"check_box"},
        {:name=>"quality_of_support_from_airport_organizations",:title=>"Quality of Support from Airport Organizations",:type=>"check_box"},
        {:name=>"quality_of_support_from_airport_vendors",:title=>"Quality of Support from Airport Vendors",:type=>"check_box"},
        {:name=>"quality_of_support_from_management",:title=>"Quality of Support from Management",:type=>"check_box"},
        {:name=>"reduced_safety_standards",:type=>"check_box"},
        {:name=>"rest/duty/flight_time",:type=>"check_box"},
        {:name=>"work_group_normal_practice_(norm)",:type=>"check_box"},
        {:name=>"work_process/procedure",:type=>"check_box"},
        {:name=>"work_process/procedure_not_documented",:title=>"Work Process/Procedure not Documented",:type=>"check_box"},
        {:name=>"work_process/procedure_not_followed",:title=>"Work Process/Procedure not Followed",:type=>"check_box"},
        {:name=>"other_organizational_factors",:type=>"text_field"}
      ],
      'Policy Issues'=> [
        {:name=>"conflicting",:type=>"check_box"},
        {:name=>"inadequate",:type=>"check_box"},
        {:name=>"ineffective",:type=>"check_box"},
        {:name=>"non_existent",:type=>"check_box"},
        {:name=>"not_documented",:type=>"check_box"},
        {:name=>"not_followed",:type=>"check_box"},
        {:name=>"other",:type=>"text_field"}
      ],
      'Procedure Issues'=> [
        {:name=>"conflicting",:type=>"check_box"},
        {:name=>"inadequate",:type=>"check_box"},
        {:name=>"ineffective",:type=>"check_box"},
        {:name=>"non_existent",:type=>"check_box"},
        {:name=>"not_documented",:type=>"check_box"},
        {:name=>"not_followed",:type=>"check_box"},
        {:name=>"other",:type=>"text_field"}
      ],
      'Process Management Issues'=> [
        {:name=>"inadequate",:type=>"check_box"},
        {:name=>"ineffective",:type=>"check_box"},
        {:name=>"non_existent",:type=>"check_box"},
        {:name=>"not_documented",:type=>"check_box"},
        {:name=>"not_followed",:type=>"check_box"},
        {:name=>"other",:type=>"text_field"}
      ],
      'Responsibility Issues'=> [
        {:name=>"conflicting",:type=>"check_box"},
        {:name=>"inadequate",:type=>"check_box"},
        {:name=>"ineffective",:type=>"check_box"},
        {:name=>"non_existent",:type=>"check_box"},
        {:name=>"not_documented",:type=>"check_box"},
        {:name=>"other",:type=>"text_field"}
      ],
      'Root Cause'=> [
        {:name=>"primary_root_cause",:type=>"select",:options=>["Communication - Misunderstood verbal communications","Communication - Non-standard turnover / turnover process not used","Communication - Not timely","Human Factors - Condition of Operation","Human Factors - Decision Based Error","Human Factors - Perceptiual Error","Human Factors - Personell Factors","Human Factors - Skill-Based Error","Human Factors - Technological (Human Engineering)","Human Factors - Work Environment","Organizational Influences - Climate","Organizational Influences - Equip/Materials not properly maintained/needs improvement","Organizational Influences - Facility design needs improvement","Organizational Influences - ","Organizational Influences - Inadequate manpower/resources","Organizational Influences - Not funded","Procedure - Followed incorrectly","Procedure - Inadequate/need improvement","Procedure - Not developed","Procedure - Not followed","QC - Inspection instruction inadequate/not available","QC - Inspection not required","QC - Inspection techniques inadequate","Supervision/Management Systems - Corrective Actions","Supervision/Management Systems - Failure to Correct Problem","Supervision/Management Systems - Inadequate Supervision","Supervision/Management Systems - Management oversight needs improvement","Supervision/Management Systems - Planned Inappropriate Operation","Supervision/Management Systems - Standards, Policies or Admin Controls","Supervision/Management Systems - Supervisory Violation","Training - Did not exist/not implemented","Training - Did not understand training","Training - Needs improvement"]},
        {:name=>"secondary_root_cause",:type=>"select",:options=>["Communication - Misunderstood verbal communications","Communication - Non-standard turnover / turnover process not used","Communication - Not timely","Human Factors - Condition of Operation","Human Factors - Decision Based Error","Human Factors - Perceptiual Error","Human Factors - Personell Factors","Human Factors - Skill-Based Error","Human Factors - Technological (Human Engineering)","Human Factors - Work Environment","Organizational Influences - Climate","Organizational Influences - Equip/Materials not properly maintained/needs improvement","Organizational Influences - Facility design needs improvement","Organizational Influences - ","Organizational Influences - Inadequate manpower/resources","Organizational Influences - Not funded","Procedure - Followed incorrectly","Procedure - Inadequate/need improvement","Procedure - Not developed","Procedure - Not followed","QC - Inspection instruction inadequate/not available","QC - Inspection not required","QC - Inspection techniques inadequate","Supervision/Management Systems - Corrective Actions","Supervision/Management Systems - Failure to Correct Problem","Supervision/Management Systems - Inadequate Supervision","Supervision/Management Systems - Management oversight needs improvement","Supervision/Management Systems - Planned Inappropriate Operation","Supervision/Management Systems - Standards, Policies or Admin Controls","Supervision/Management Systems - Supervisory Violation","Training - Did not exist/not implemented","Training - Did not understand training","Training - Needs improvement"]}

      ],
      'Station Operation Issues'=> [
        {:name=>"station_operation_issues",:type=>"check_box"},
        {:name=>"access_panel_left_open",:type=>"check_box"},
        {:name=>"air_conditioning/pressurization",:type=>"check_box"},
        {:name=>"air_start",:type=>"check_box"},
        {:name=>"ccsm",:title=>"CCSM",:type=>"check_box"},
        {:name=>"computer",:type=>"check_box"},
        {:name=>"crew_hotel/transportation",:type=>"check_box"},
        {:name=>"de-icing",:title=>"De-Icing",:type=>"check_box"},
        {:name=>"display",:type=>"check_box"},
        {:name=>"flight_controls",:type=>"check_box"},
        {:name=>"gen/line_malfunction",:type=>"check_box"},
        {:name=>"hazmat",:title=>"HAZMAT",:type=>"check_box"},
        {:name=>"intercom",:type=>"check_box"},
        {:name=>"procedures",:type=>"check_box"},
        {:name=>"remote_dispatch",:type=>"check_box"},
        {:name=>"weather_resources",:type=>"check_box"},
        {:name=>"other_station_operation_issues",:type=>"text_field"}
      ],
      'Station Ops Complicaiton-Customer Service Attributes'=> [
        {:name=>"station_ops_complications-customer_service",:title=>"Station Ops Complications-Customer Service",:type=>"check_box"},
        {:name=>"ada",:title=>"ADA",:type=>"check_box"},
        {:name=>"agent_availability",:type=>"check_box"},
        {:name=>"agent_closed_boarding_door",:title=>"Agent closed boarding door",:type=>"check_box"},
        {:name=>"aislechair",:type=>"check_box"},
        {:name=>"baggage_claim",:type=>"check_box"},
        {:name=>"baggage_non-compliance_quantity",:title=>"Baggage Non-Compliance Quantity",:type=>"check_box"},
        {:name=>"baggage_non-compliance_size",:title=>"Baggage Non-Compliance Size",:type=>"check_box"},
        {:name=>"board_room",:type=>"check_box"},
        {:name=>"boarding",:type=>"check_box"},
        {:name=>"deplanning",:type=>"check_box"},
        {:name=>"gate_staff",:type=>"check_box"},
        {:name=>"jetbridge_operations",:type=>"check_box"},
        {:name=>"passenger_count_incorrect",:type=>"check_box"},
        {:name=>"passenger_dissatisfied",:type=>"check_box"},
        {:name=>"seat_assignment",:type=>"check_box"},
        {:name=>"security",:type=>"check_box"},
        {:name=>"station_appearance",:type=>"check_box"},
        {:name=>"supplies",:type=>"check_box"},
        {:name=>"ticketing",:type=>"check_box"},
        {:name=>"unaccompanied_minor",:type=>"check_box"},
        {:name=>"other_station_ops_complications-customer_service",:title=>"Other Station Ops Complications-Customer Service",:type=>"text_field"}
      ],
      'Technical Data Error'=> [
        {:name=>"technical_data_error",:type=>"check_box"},
        {:name=>"improper_mel/deferral",:title=>"Improper MEL/Deferral",:type=>"check_box"},
        {:name=>"manuals",:type=>"check_box"},
        {:name=>"reference_material",:type=>"check_box"},
        {:name=>"work_card",:type=>"check_box"},
        {:name=>"other_technical_data",:type=>"text_field"}
      ],
      'Technical Knowledge/Skills'=> [
        {:name=>"technical_knowledge/skills/training",:type=>"check_box"},
        {:name=>"aircraft_configuration_knowledge",:type=>"check_box"},
        {:name=>"computing_skills",:type=>"check_box"},
        {:name=>"english_language_proficiency",:type=>"check_box"},
        {:name=>"inadequate_aircraft_system_knowledge",:type=>"check_box"},
        {:name=>"inadequate_airline_process_knowledge",:type=>"check_box"},
        {:name=>"inadequate_skills",:type=>"check_box"},
        {:name=>"inadequate_task_experience",:type=>"check_box"},
        {:name=>"inadequate_task_knowledge",:type=>"check_box"},
        {:name=>"inadequate_task_planning",:type=>"check_box"},
        {:name=>"teamwork_skills",:type=>"check_box"},
        {:name=>"training_issues",:type=>"select",:options=>['Incorrect','Lack of','No','Other','Yes']},
        {:name=>"training_situation",:type=>"select",:options=>['Instructing','Other','Receiving Training']},
        {:name=>"other_technical_knowledge/skills/training",:type=>"text_field"}
      ],
      'Training : Central Load Planners'=> [
        {:name=>"dispatcher_training",:type=>"check_box"},
        {:name=>"cockpit_jump_seat_observation",:type=>"check_box"},
        {:name=>"communications",:type=>"check_box"},
        {:name=>"drm_training",:title=>"DRM Training",:type=>"check_box"},
        {:name=>"decisionmaking",:type=>"check_box"},
        {:name=>"deferred_items-mel/cdl",:title=>"Deferred Items-MEL/CDL",:type=>"check_box"},
        {:name=>"field_conditions",:type=>"check_box"},
        {:name=>"flight_planning-initial",:title=>"Flight Planning-Initial",:type=>"check_box"},
        {:name=>"flight_releases",:type=>"check_box"},
        {:name=>"initial",:type=>"check_box"},
        {:name=>"notams",:title=>"NOTAMs",:type=>"check_box"},
        {:name=>"operational_control",:type=>"check_box"},
        {:name=>"policies/procedures",:type=>"check_box"},
        {:name=>"recurrent",:type=>"check_box"},
        {:name=>"other_dispatcher_training",:type=>"text_field"}
      ],
      'Training : Customer Sevice Representatives Attributes' => [
        {:name=>"customer_service_representative_training",:type=>"check_box"},
        {:name=>"documentation",:type=>"check_box"},
        {:name=>"passenger_carry_ons",:type=>"check_box"},
        {:name=>"policies/procedures",:type=>"check_box"},
        {:name=>"security",:type=>"check_box"},
        {:name=>"special_handling_passengers",:type=>"check_box"},
        {:name=>"other_customer_service_representative_training",:type=>"text_field"}
      ],
      'Training : Dispatchers'=> [
        {:name=>"dispatcher_training",:type=>"check_box"},
        {:name=>"cockpit_jump_seat_observation",:type=>"check_box"},
        {:name=>"communications",:type=>"check_box"},
        {:name=>"drm_training",:title=>"DRM Training",:type=>"check_box"},
        {:name=>"decisionmaking",:type=>"check_box"},
        {:name=>"deferred_items-mel/cdl",:title=>"Deferred Items-MEL/CDL",:type=>"check_box"},
        {:name=>"field_conditions",:type=>"check_box"},
        {:name=>"flight_planning-initial",:title=>"Flight Planning-Initial",:type=>"check_box"},
        {:name=>"flight_releases",:type=>"check_box"},
        {:name=>"initial",:type=>"check_box"},
        {:name=>"notams",:title=>"NOTAMs",:type=>"check_box"},
        {:name=>"operational_control",:type=>"check_box"},
        {:name=>"policies/procedures",:type=>"check_box"},
        {:name=>"recurrent",:type=>"check_box"},
        {:name=>"other_dispatcher_training",:type=>"text_field"}
      ],
      'Training : Flight Attendants'=> [
        {:name=>"flight_attendants_training",:type=>"check_box"},
        {:name=>"cabin_maintenance_log",:type=>"check_box"},
        {:name=>"computer_based_training",:type=>"check_box"},
        {:name=>"drills",:type=>"check_box"},
        {:name=>"emergency_equipment",:type=>"check_box"},
        {:name=>"initial",:type=>"check_box"},
        {:name=>"life_support",:type=>"check_box"},
        {:name=>"overwater",:type=>"check_box"},
        {:name=>"policies/procedures",:type=>"check_box"},
        {:name=>"recurrent",:type=>"check_box"},
        {:name=>"reports",:type=>"check_box"},
        {:name=>"security",:type=>"check_box"},
        {:name=>"other_flight_attendants_training",:type=>"text_field"}
      ],
      'Training : Ground Service Technicians Attributes'=> [
        {:name=>"ground_service_technicians_training",:type=>"check_box"},
        {:name=>"hazmat",:title=>"HAZMAT",:type=>"check_box"},
        {:name=>"marshalling",:type=>"check_box"},
        {:name=>"policies/procedures",:type=>"check_box"},
        {:name=>"pushback",:type=>"check_box"},
        {:name=>"safety_zone",:type=>"check_box"},
        {:name=>"security",:type=>"check_box"},
        {:name=>"other_ground_service_technicians_training",:type=>"text_field"}
      ],
      'Training : Maintenance Technicians'=> [
        {:name=>"maintenanace_technicians_training",:type=>"check_box"},
        {:name=>"apu_operations",:title=>"APU Operations",:type=>"check_box"},
        {:name=>"air_start",:type=>"check_box"},
        {:name=>"policies/procedures",:type=>"check_box"},
        {:name=>"taxi/tow_operations",:type=>"check_box"},
        {:name=>"other_maintenanace_technicians_training",:type=>"text_field"}
      ],
      'Training : Organization'=> [
        {:name=>"organization_training",:type=>"check_box"},
        {:name=>"publish_article",:type=>"check_box"},
        {:name=>"standardization",:type=>"check_box"},
        {:name=>"supplement",:type=>"check_box"},
        {:name=>"other_organization_training",:type=>"text_field"}
      ],
      'Training : Pilots'=> [
        {:name=>"crm",:title=>"CRM",:type=>"check_box"},
        {:name=>"computer_based_training",:type=>"check_box"},
        {:name=>"emergency_equipment",:type=>"check_box"},
        {:name=>"flight_deck_procedures",:type=>"check_box"},
        {:name=>"general_operating_systems",:type=>"check_box"},
        {:name=>"home_study",:type=>"check_box"},
        {:name=>"initial_indoctorination/awareness",:type=>"check_box"},
        {:name=>"mel",:title=>"MEL",:type=>"check_box"},
        {:name=>"overwater",:type=>"check_box"},
        {:name=>"pilot_training",:type=>"check_box"},
        {:name=>"policies/procedures",:type=>"check_box"},
        {:name=>"recurrent",:type=>"check_box"},
        {:name=>"spt",:title=>"SPT",:type=>"check_box"},
        {:name=>"simulator_pc",:title=>"Simulator PC",:type=>"check_box"},
        {:name=>"simulator_pt",:title=>"Simulator PT",:type=>"check_box"},
        {:name=>"standardization",:type=>"check_box"},
        {:name=>"systems_airbus",:type=>"select",:options=>["A300","A310","A319","A320","A321","A330","Other"]},
        {:name=>"systems_boeing",:type=>"select",:options=>["B717","B727","B737-100/200","B737-300/400/500","B747-NG","B747","B757","B767","B777","Other"]},
        {:name=>"systems_embraer",:type=>"select",:options=>["EMB-120","EMB-135","EMB-140","EMB-145","EMB-XRJ","Other"]},
        {:name=>"transition",:type=>"check_box"},
        {:name=>"upgrade",:type=>"check_box"},
        {:name=>"other_pilot_training",:type=>"text_field"}
      ],
      'Weight and Balance Event'=> [
        {:name=>"weight_and_balance",:title=>"Weight and Balance",:type=>"check_box"},
        {:name=>"actual_center_of_gravity",:title=>"Actual Center of Gravity",:type=>"text_field"},
        {:name=>"actual_load_did_not_match_inbound_load_message",:type=>"check_box"},
        {:name=>"actual_weight",:type=>"text_field"},
        {:name=>"aircraft_loaded_weight/cg_error",:title=>"Aircraft Loaded Weight/CG Error",:type=>"select",:options=>["Incorrect Bag Count","Incorrect Freight Weight","Other"]},
        {:name=>"aircraft_loaded_weight/cg_error",:title=>"Aircraft Loaded Weight/CG Error",:type=>"check_box"},
        {:name=>"cg_difference",:title=>"CG Difference",:type=>"text_field"},
        {:name=>"cg_from_datum",:title=>"CG from Datum",:type=>"check_box"},
        {:name=>"cg_from_nose",:title=>"CG from Nose",:type=>"check_box"},
        {:name=>"cpl_contacted",:title=>"CPL Contacted",:type=>"check_box"},
        {:name=>"calculation_error",:type=>"check_box"},
        {:name=>"cargo",:type=>"select",:options=>["Restrained","Other","Shifting"]},
        {:name=>"cargo_loading_error",:type=>"check_box"},
        {:name=>"cargo_shift",:type=>"check_box"},
        {:name=>"cargo/bag_documentation_error",:type=>"select",:options=>["Undocumented Cargo Loaded","Documented Cargo Not Loaded","Undocumented Bag Loaded","Undocumented Bag Loaded","Documented Bag Not Loaded","Items Not in Documented PIT","Other Count/Weight Error"]},
        {:name=>"center_of_gravity",:title=>"Center of Gravity",:type=>"check_box"},
        {:name=>"center_of_gravity_error_type",:title=>"Center of Gravity Error Type",:type=>"select",:options=>["Cargo/Bags in Wrong Location","Igloos/Cargo Containers in Wrong Location"]},
        {:name=>"exceeded_cg-limitations",:title=>"Exceeded CG limitations",:type=>"check_box"},
        {:name=>"exceeded_pit/uld_limitations",:title=>"Exceeded PIT/ULD limitations",:type=>"check_box"},
        {:name=>"exceeded_running_load_restrictions",:title=>"Exceeded running load restrictions",:type=>"check_box"},
        {:name=>"incorrect_planning_tool_used",:type=>"check_box"},
        {:name=>"imput_error",:type=>"check_box"},
        {:name=>"items_not_in_documented_pit",:title=>"Items not in Documented Pit",:type=>"check_box"},
        {:name=>"load_verificaton_error",:type=>"check_box"},
        {:name=>"mtow_exceeded",:title=>"MTOW Exceeded",:type=>"check_box"},
        {:name=>"maximum_landing_weight_(lbs)",:title=>"Maximum Landing Weight (lbs)",:type=>"text_field"},
        {:name=>"maximum_takeoff_weight_(lbs)",:title=>"Maximum Takeoff Weight (lbs)",:type=>"text_field"},
        {:name=>"maximum_taxi_weight_(lbs)",:title=>"Maximum Taxi Weight (lbs)",:type=>"text_field"},
        {:name=>"maximum_zero_fuel_weight_(lbs)",:title=>"Maximum Zero Fuel Weight (lbs)",:type=>"text_field"},
        {:name=>"over_max_zero_fuel_weight",:type=>"check_box"},
        {:name=>"over_release_weight",:type=>"check_box"},
        {:name=>"overweight_takeoff",:type=>"check_box"},
        {:name=>"overweight_taxi",:type=>"check_box"},
        {:name=>"overweight_for_ground_surface_limits",:title=>"Overweight for Ground Surface Limits",:type=>"check_box"},
        {:name=>"passenger_loading/count_error",:type=>"check_box"},
        {:name=>"passenger_loading/count_error_type",:type=>"select",:options=>["Incorrect Count","Zone Distribution Error","Jump Seat Error"]},
        {:name=>"payload>10,000_kgs",:type=>"check_box"},
        {:name=>"reported_center_of_gravity",:title=>"Reported Center of Gravity",:type=>"text_field"},
        {:name=>"reported_weight",:type=>"text_field"},
        {:name=>"reported_zfw",:title=>"Reported ZFW",:type=>"check_box"},
        {:name=>"shelf_weight_exceedence",:type=>"check_box"},
        {:name=>"center_of_gravity_location_at_time_of_accident/incident_in_inches",:title=>"Center of Gravity Location at Time of Accident/Incident in Inches",:type=>"text_field"},
        {:name=>"percent_mean_aerodynamic_cord_(%mac)",:title=>"Percent Mean Aerodynamic Cord (%MAC)",:type=>"text_field"},
        {:name=>"actual_zfw",:title=>"Actual ZFW",:type=>"text_field"},
        {:name=>"other_weight_and_balance_event",:title=>"Other Weight and Balance Event",:type=>"text_field"},
        {:name=>"reported_zfw",:title=>"Reported ZFW",:type=>"text_field"},
        {:name=>"weight_difference",:type=>"text_field"}
      ]
    }
  end
end
