class FindingDescription < Cause
	belongs_to :finding,foreign_key:"owner_id",class_name:"Finding"

	def self.get_headers
		[
			{:title=>"Category",:field=>"category"},
			{:title=>"Attribute",:field=>"get_attr"},
			{:title=>"Value",:field=>"get_value"}
		]
	end
	
	def get_value
		if self.value=="true"
			"Yes"
		else
			self.value
		end
	end

	def get_attr
		Rails.logger.debug "self.category=#{self.category}"
		self.class.categories[self.category].each do |c|
			if c[:name]==self.send('attr')
				return c[:title].present? ? c[:title] : c[:name].titleize
			end
		end
	end

	#old
	# def self.categories
	# 	super.merge(
	# 	{
	# 		'ATOS Elements' => [
	# 			{:name=>"authority",:type=>"check_box"},
	# 			{:name=>"controls",:type=>"check_box"},
	# 			{:name=>"interfaces",:type=>"check_box"},
	# 			{:name=>"policy",:type=>"check_box"},
	# 			{:name=>"procedures",:type=>"check_box"},
	# 			{:name=>"process_measures",:type=>"check_box"},
	# 			{:name=>"responsibility",:type=>"check_box"},
	# 			{:name=>"other",:type=>"text_field"}
	# 		],
	# 		'Cabin Equipment'=> [
	# 			{:name=>"cabin_equipment",:type=>"check_box"},
	# 			{:name=>"66n_o2",:title=>"66N O2",:type=>"check_box"},
	# 			{:name=>"aed",:title=>"AED",:type=>"check_box"},
	# 			{:name=>"aed_serial_no",:title=>"AED Serial No",:type=>"text_field"},
	# 			{:name=>"blood_pressure_cuff",:type=>"check_box"},
	# 			{:name=>"briefing_cards",:type=>"check_box"},
	# 			{:name=>"cd_player",:title=>"CD Player",:type=>"select",:options=>['Failure','Other','Overheat','Smoke/Fumes']},
	# 			{:name=>"cart_repair_tag_no",:type=>"text_field"},
	# 			{:name=>"ceiling_panel",:type=>"select",:options=>['Other','Unsecured']},
	# 			{:name=>"circuit_breakers_pulled",:type=>"check_box"},
	# 			{:name=>"closet",:type=>"select",:options=>["Failure","Jammed","Other","Smoke/Fumes","Unsecured"]},
	# 			{:name=>"coffee_maker",:type=>"select",:options=>["Failure","Other","Smoke/Fumes","Unsecured","Foreign Material Inside","Foreign Material On/Under"]},
	# 			{:name=>"communication_system",:type=>"select",:options=>["Failure","Other"]},
	# 			{:name=>"crash_ax",:type=>"check_box"},
	# 			{:name=>"crew_oxygen_system",:type=>"check_box"},
	# 			{:name=>"demo_equipment_pouches",:type=>"check_box"},
	# 			{:name=>"elts",:type=>"check_box",:title=>"ELTs"},
	# 			{:name=>"emk_eemk",:type=>"check_box",:title=>"EMK/EEMK"},
	# 			{:name=>"emergency_safety_equipment",:type=>"check_box",:title=>"Emergency/Safety Equipment"},
	# 			{:name=>"entertainment_system",:type=>"select",:options=>['Failure','Other','Overheat','Smoke/Fumes']},
	# 			{:name=>"fa_breakaway_flashlight",:type=>"check_box",:title=>"F/A Breakaway Flashlight"},
	# 			{:name=>"first_aid_kit",:type=>"check_box"},
	# 			{:name=>"gallery_cart",:type=>"select",:options=>['Availability','Brake/Wheels','Drawers','Locks','Other','Sharp Edges','Smoke/Fumes','Unsecured']},
	# 			{:name=>"gallarty_cart_equipment_repair_tag_no",:title=>"Gallarty Cart-Equipment Repair Tag No",:type=>"text_field"},
	# 			{:name=>"gallery_storage_bins",:type=>"select",:options=>['Jammed','Other','Unsecured']},				
	# 			{:name=>"halon_fire_extinguisher",:type=>"check_box"},
	# 			{:name=>"ice_bucket",:type=>"check_box"},
	# 			{:name=>"jumpseat",:type=>"select",:options=>['Authorization','Broken','Cushion','Harness','Seat Belt','Stowage','Other']},
	# 			{:name=>"lavatory",:type=>"select",:options=>['Failure','Other','Sink','Smoke/Fumes','Toilet','Water Overflow']},
	# 			{:name=>"life_jackets",:type=>"check_box"},
	# 			{:name=>"life_raft",:type=>"check_box"},
	# 			{:name=>"lithium_ion_battery",:type=>"check_box"},
	# 			{:name=>"megaphone",:type=>"check_box"},
	# 			{:name=>"onboard_wheelchair",:type=>"check_box"},
	# 			{:name=>"other_emergency_equipment",:type=>"text_field"},
	# 			{:name=>"other_gallery_equipement",:type=>"check_box"},
	# 			{:name=>"other_gallery_equipement-compartment_number",:type=>"text_field"},
	# 			{:name=>"oven",:type=>'select',:options=>["Failure","Other","Smoke/Fumes","Unsecured","Foreign Material Inside","Foreign Material On/Under"]},
	# 			{:name=>"overhead_bin",:type=>"select",:options=>['Bag Shift','Failure','Jammed','Smoke/Fumes','Other','Unsecured']},
	# 			{:name=>"oxygen_box_tool",:type=>"check_box"},
	# 			{:name=>"pbe",:type=>"check_box",:title=>"PBE"},
	# 			{:name=>"passenger_oxygen_system",:type=>"check_box"},
	# 			{:name=>"passenger_seat",:type=>"select",:options=>['Cushion','Harness','Recline','Seat Belt','Track','Tray Table','Other']},
	# 			{:name=>"portable_oxygen_bottle",:type=>"check_box"},
	# 			{:name=>"portable_oxygen_concentrator",:type=>"check_box"},
	# 			{:name=>"smoke_detectors",:type=>"select",:options=>['Activated','Failure','Vandalized','Other']},
	# 			{:name=>"smoke_goggles",:type=>"check_box"},
	# 			{:name=>"solid_state_o2",:type=>"check_box"},
	# 			{:name=>"supplemental_oxygen",:type=>"check_box"},
	# 			{:name=>"trash_containers",:type=>"select",:options=>['Other','Smoke/Fumes']},
	# 			{:name=>"wall_panel",:type=>"select",:options=>["Other","Unsecured"]},
	# 			{:name=>"water_fire_extinguisher",:type=>"check_box"},
	# 			{:name=>"door_indication",:type=>"text_field"},
	# 			{:name=>"other_cabin_equipment",:type=>"text_field"},
	# 			{:name=>"serial_number",:type=>"text_field"}
	# 		]
	# 	}).sort.to_h
	# end

	def self.categories
	  ({
	    "ATOS Elements" => [
	      {name: "Authority", type: "check_box"},
	      {name: "Controls", type: "check_box"},
	      {name: "Interfaces", type: "check_box"},
	      {name: "Policy", type: "check_box"},
	      {name: "Procedures", type: "check_box"},
	      {name: "Process Measures", type: "check_box"},
	      {name: "Responsibility", type: "check_box"},
	      {name: "Other", type: "text_field"},
	    ],
	    "Authority Issues" => [
	      {name: "Conflicting", type: "check_box"},
	      {name: "Inadequate", type: "check_box"},
	      {name: "Ineffective", type: "check_box"},
	      {name: "Non Existent", type: "check_box"},
	      {name: "Not Documented", type: "check_box"},
	      {name: "Not Known", type: "check_box"},
	      {name: "Other", type: "text_field"},
	    ],
	    "Cabin Equipment" => [
	      {name: "Cabin Equipment", type: "check_box"},
	      {name: "66N O2", type: "check_box"},
	      {name: "AED", type: "check_box"},
	      {name: "AED Serial No", type: "text_field"},
	      {name: "Blood Pressure Cuff", type: "check_box"},
	      {name: "Briefing Cards", type: "check_box"},
	      {name: "CD Player", type: "select", options: ["Failure","Other","Overheat","Smoke/Fumes"]},
	      {name: "Cart Repair Tag No", type: "text_field"},
	      {name: "Ceiling Panel", type: "select", options: ["Other","Unsecured"]},
	      {name: "Circuit Breakers Pulled", type: "check_box"},
	      {name: "Closet", type: "select", options: ["Failure","Jammed","Other","Smoke/Fumes","Unsecured"]},
	      {name: "Coffee Maker", type: "select", options: ["Failure","Other","Smoke/Fumes","Unsecured","Foreign Material Inside","Foreign Material On/Under"]},
	      {name: "Communication System", type: "select", options: ["Failure","Other"]},
	      {name: "Crash Ax", type: "check_box"},
	      {name: "Crew Oxygen System", type: "check_box"},
	      {name: "Demo Equipment Pouches", type: "check_box"},
	      {name: "ELTs", type: "check_box"},
	      {name: "EMK/EEMK", type: "check_box"},
	      {name: "Emergency/Safety Equipment", type: "check_box"},
	      {name: "Entertainment System", type: "select", options: ["Failure","Other","Overheat","Smoke/Fumes"]},
	      {name: "F/A Breakaway Flashlight", type: "check_box"},
	      {name: "First Aid Kit", type: "check_box"},
	      {name: "Galley Cart", type: "select", options: ["Availability","Brakes/Wheels","Drawers","Locks","Other","Sharp Edges","Smoke/Fumes","Unsecured"]},
	      {name: "Galley Cart-Equipment Repair Tag No", type: "text_field"},
	      {name: "Galley Storage Bins", type: "select", options: ["Jammed","Other","Unsecured"]},
	      {name: "Halon Fire Extinguisher", type: "check_box"},
	      {name: "Ice Bucket", type: "check_box"},
	      {name: "Jumpseat", type: "select", options: ["Authorization","Broken","Cushion","Harness","Other","Seat Belt","Stowage"]},
	      {name: "Lavatory", type: "select", options: ["Failure","Other","Sink","Smoke/Fumes","Toilet","Water Overflow"]},
	      {name: "Life Jackets", type: "check_box"},
	      {name: "Life Raft", type: "check_box"},
	      {name: "Lithium Ion Battery", type: "check_box"},
	      {name: "Megaphone", type: "check_box"},
	      {name: "Onboard Wheelchair", type: "check_box"},
	      {name: "Other Emergency Equipment", type: "text_field"},
	      {name: "Other Galley Equipment", type: "check_box"},
	      {name: "Other Galley Equipment-Compartment Number", type: "text_field"},
	      {name: "Oven", type: "select", options: ["Failure","Other","Smoke/Fumes","Unsecured","Foreign Material Inside","Foreign Material On/Under"]},
	      {name: "Overhead Bin", type: "select", options: ["Bag Shift","Failure","Jammed","Other","Smoke/Fumes","Unsecured"]},
	      {name: "Oxygen Box Tool", type: "check_box"},
	      {name: "PBE", type: "check_box"},
	      {name: "Passenger Oxygen System", type: "check_box"},
	      {name: "Passenger Seat", type: "select", options: ["Cushion","Harness","Other","Recline","Seat Belt","Track","Tray Table"]},
	      {name: "Portable Oxygen Bottle", type: "check_box"},
	      {name: "Portable Oxygen Concentrator", type: "check_box"},
	      {name: "Smoke Detectors", type: "select", options: ["Activated","Failure","Other","Vandalized"]},
	      {name: "Smoke Goggles", type: "check_box"},
	      {name: "Solid State O2", type: "check_box"},
	      {name: "Supplemental Oxygen", type: "check_box"},
	      {name: "Trash Containers", type: "select", options: ["Other","Smoke/Fumes"]},
	      {name: "Wall Panel", type: "select", options: ["Other","Unsecured"]},
	      {name: "Water Fire Extinguisher", type: "check_box"},
	      {name: "Door Indication", type: "text_field"},
	      {name: "Other Cabin Equipment", type: "text_field"},
	      {name: "Serial Number", type: "text_field"},
	    ],
	    "Communication" => [
	      {name: "Conflicting", type: "check_box"},
	      {name: "Inadequate", type: "check_box"},
	      {name: "Incorrect", type: "check_box"},
	      {name: "Ineffective", type: "check_box"},
	      {name: "Non Existent", type: "check_box"},
	      {name: "Verbal", type: "check_box"},
	      {name: "Written", type: "check_box"},
	      {name: "Other", type: "text_field"},
	    ],
	    "Company Manuals" => [
	      {name: "Company Manuals", type: "check_box"},
	      {name: "Company Manuals-ATC", type: "check_box"},
	      {name: "Customer Service Manual", type: "check_box"},
	      {name: "Dispatch Manuals", type: "check_box"},
	      {name: "Electronic Manual", type: "check_box"},
	      {name: "Emergency Response Manual", type: "check_box"},
	      {name: "FCOM/AOM", type: "check_box"},
	      {name: "FOM", type: "check_box"},
	      {name: "FSM", type: "check_box"},
	      {name: "Ground Operations Manuals", type: "check_box"},
	      {name: "IOM", type: "check_box"},
	      {name: "MEL", type: "check_box"},
	      {name: "MPPM", type: "check_box"},
	      {name: "Quick Reference Handbook", type: "check_box"},
	      {name: "Shipsets", type: "select", options: ["Not Revised","Incorrect Books","Incomplete"]},
	      {name: "Other Company Manuals", type: "text_field"},
	    ],
	    "Control Issues" => [
	      {name: "Inadequate", type: "check_box"},
	      {name: "Ineffective", type: "check_box"},
	      {name: "Non Existent", type: "check_box"},
	      {name: "Not Documented", type: "check_box"},
	      {name: "Not Followed", type: "check_box"},
	      {name: "Other", type: "text_field"},
	    ],
	    "Documentation Error" => [
	      {name: "Documentation Error", type: "check_box"},
	      {name: "Closed in Error", type: "check_box"},
	      {name: "Conflicting Maintenance Document", type: "check_box"},
	      {name: "Confusing Software", type: "check_box"},
	      {name: "Incorrect Paperwork/Log Book Entry", type: "check_box"},
	      {name: "Incorrect Reference", type: "check_box"},
	      {name: "Maintenance Not Scheduled", type: "check_box"},
	      {name: "Missed Recertification/Downgrade", type: "check_box"},
	      {name: "Missing Airworthiness Release", type: "check_box"},
	      {name: "Missing Paperwork/Log Book Entry", type: "check_box"},
	      {name: "Not Documented", type: "check_box"},
	      {name: "Reference Data Not Used", type: "check_box"},
	      {name: "Specifications", type: "check_box"},
	      {name: "Work Card Error", type: "check_box"},
	      {name: "Other Documentation Error", type: "text_field"},
	    ],
	    "Emergency Contingency Management" => [
	      {name: "Execution", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Planning", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Preparation", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	    ],
	    "Environment" => [
	      {name: "Environment", type: "check_box"},
	      {name: "Congested", type: "check_box"},
	      {name: "Day", type: "check_box"},
	      {name: "Indoor", type: "check_box"},
	      {name: "Lighting", type: "check_box"},
	      {name: "Lighting - Artificial", type: "check_box"},
	      {name: "Lighting - Natural ", type: "check_box"},
	      {name: "Night", type: "check_box"},
	      {name: "Noise Levels: Excessive", type: "check_box"},
	      {name: "Noise Levels: High", type: "check_box"},
	      {name: "Noise Levels: Marginal", type: "check_box"},
	      {name: "Noise Levels: Normal", type: "check_box"},
	      {name: "Outdoor", type: "check_box"},
	      {name: "Rough Terrain", type: "check_box"},
	      {name: "Surface: Contaminated", type: "check_box"},
	      {name: "Surface: Dry", type: "check_box"},
	      {name: "Surface: Ice", type: "check_box"},
	      {name: "Surface: Snow", type: "check_box"},
	      {name: "Surface: Wet", type: "check_box"},
	      {name: "Temperature: Cold", type: "check_box"},
	      {name: "Temperature: Hot", type: "check_box"},
	      {name: "Temperature: Moderate", type: "check_box"},
	      {name: "Tight Conditions", type: "check_box"},
	      {name: "Vibrations", type: "check_box"},
	      {name: "Visibility: Dawn", type: "check_box"},
	      {name: "Visibility: Dusk", type: "check_box"},
	      {name: "Visibility: Fair", type: "check_box"},
	      {name: "Visibility: Glare", type: "check_box"},
	      {name: "Visibility: Good", type: "check_box"},
	      {name: "Visibility: Marginal", type: "check_box"},
	      {name: "Visibility: Other", type: "text_field"},
	      {name: "Visibility: Poor", type: "check_box"},
	      {name: "Visual Obstruction", type: "check_box"},
	      {name: "Weather - Ice", type: "check_box"},
	      {name: "Other Environment", type: "text_field"},
	    ],
	    "Equipment/Tools/Safety Equipment" => [
	      {name: "Equipment/Tools/Safety Equipment", type: "check_box"},
	      {name: "Cannot Use in Intended Environment", type: "check_box"},
	      {name: "Inappropriate for the Task", type: "check_box"},
	      {name: "Incorrectly Labeled/Marked", type: "check_box"},
	      {name: "Incorrectly Used", type: "check_box"},
	      {name: "Lost Tool", type: "check_box"},
	      {name: "Miscalibrated", type: "check_box"},
	      {name: "No Instructions", type: "check_box"},
	      {name: "Not Available or Broken", type: "check_box"},
	      {name: "Not Labeled/Marked", type: "check_box"},
	      {name: "Not Used", type: "check_box"},
	      {name: "PPE/CPE Not Used", type: "check_box"},
	      {name: "PPE/CPE Used Incorrectly", type: "check_box"},
	      {name: "Past Expiration Date", type: "check_box"},
	      {name: "Poor Layout of Controls or Displays", type: "check_box"},
	      {name: "Safety Tags Not Used", type: "check_box"},
	      {name: "Too Complicated", type: "check_box"},
	      {name: "Unreliable", type: "check_box"},
	      {name: "Unsafe", type: "check_box"},
	      {name: "Other Equipment/Tools/Safety Equipment", type: "text_field"},
	    ],
	    "Event Information" => [
	      {name: "Activity at Time of Event", type: "text_field"},
	      {name: "Aircraft", type: "check_box"},
	      {name: "Aircraft Zone", type: "text_field"},
	      {name: "Aware Time of Day", type: "select", options: ["Dawn","Daylight","Dusk","Night","Unknown"]},
	      {name: "CFR Violation", type: "check_box"},
	      {name: "CFR Violation Part No", type: "text_field"},
	      {name: "Cabin Phases", type: "select", options: ["boarding","departure","gate arrival","deplanning","pre-flight","non-flight","in-flight"]},
	      {name: "Cargo", type: "check_box"},
	      {name: "Catering", type: "check_box"},
	      {name: "Charter/Ferry Flight", type: "check_box"},
	      {name: "Club", type: "check_box"},
	      {name: "Component/System/Subsystem Involved", type: "text_area"},
	      {name: "Equipment Type", type: "text_field"},
	      {name: "Event Location", type: "text_field"},
	      {name: "Event Time of Day", type: "select", options: ["Dawn","Daylight","Dusk","Night","Unknown"]},
	      {name: "FBO", type: "check_box"},
	      {name: "GSE", type: "check_box"},
	      {name: "Location in Aircraft at Time of Event", type: "text_field"},
	      {name: "Office-Environment", type: "check_box"},
	      {name: "Operation Domestic/International", type: "select", options: ["Domestic","International"]},
	      {name: "Operator", type: "select", options: ["Air Carrier","Repair Station"]},
	      {name: "Plant MX", type: "check_box"},
	      {name: "Quality Escape", type: "check_box"},
	      {name: "Safety Concern", type: "check_box"},
	      {name: "Scheduled Maintenance", type: "check_box"},
	      {name: "Shift of Error", type: "select", options: ["Days","Evening","Graveyard","Relief","Other"]},
	      {name: "Shift of Error (Other)", type: "text_field"},
	      {name: "Station Event Reported", type: "select", options: ["ATL","BDL","BOS","BWI","CID","CLT","CMH","DCA","DEN","DFW","ELP","EWR","FLL","IAD","JFK","JQF","LAS","LAX","LGA","MCO","MIA","ORD","ORF","PHL","PHX","PIT","PVD","RIC","SAN","SEA","SFO","SNA","TPA"]},
	      {name: "Station Event Reported (Other)", type: "text_field"},
	      {name: "Stores", type: "check_box"},
	      {name: "Taxi", type: "check_box"},
	      {name: "Three-Hour Tarmac Rule", type: "check_box"},
	      {name: "Ticket Counter", type: "check_box"},
	      {name: "Time Since Takeoff (Minutes)", type: "text_field"},
	      {name: "Type of Maintenance", type: "select", options: ["Base","Line","Other"]},
	      {name: "Type of Maintenance or Check Being Performed", type: "text_field"},
	      {name: "Was Comp Check Being Conducted", type: "select", options: ["Yes","No"]},
	      {name: "Was OJT Being Conducted", type: "select", options: ["Yes","No"]},
	      {name: "Was the Event Aircraft-related?", type: "check_box"},
	      {name: "Event Classification", type: "select", options: ["Enterprise Event","Near Miss","Non-Reportable","Unknown/Undertermined"]},
	      {name: "Was procedure/SOP followed", type: "select", options: ["yes","no"]},
	      {name: "Was there a Company Procedure", type: "select", options: ["yes","no"]},
	      {name: "Was this incident preventable", type: "select", options: ["yes","no"]},
	      {name: "Air Carrier Code", type: "select", options: [""]},
	      {name: "Air Carrier Code (Other)", type: "text_field"},
	      {name: "Station Code", type: "select", options: ["ATL","BDL","BOS","BWI","CID","CLT","CMH","DCA","DEN","DFW","ELP","EWR","FLL","IAD","JFK","JQF","LAS","LAX","LGA","MCO","MIA","ORD","ORF","PHL","PHX","PIT","PVD","RIC","SAN","SEA","SFO","SNA","TPA"]},
	      {name: "Station Code (Other)", type: "text_field"},
	      {name: "Vendor", type: "select", options: [""]},
	      {name: "Vendor (Other)", type: "text_field"},
	      {name: "Gate", type: "check_box"},
	      {name: "Gate Number", type: "text_field"},
	      {name: "Hangar", type: "check_box"},
	      {name: "In-Flight", type: "check_box"},
	      {name: "Ramp", type: "check_box"},
	      {name: "Other Location", type: "text_field"},
	      {name: "Customer Name", type: "text_field"},
	    ],
	    "Facilities" => [
	      {name: "Facilities", type: "check_box"},
	      {name: "Access (Ladders, Stands)", type: "check_box"},
	      {name: "Artificial Lighting: Fair", type: "check_box"},
	      {name: "Artificial Lighting: Good", type: "check_box"},
	      {name: "Artificial Lighting: Marginal", type: "check_box"},
	      {name: "Artificial Lighting: None", type: "check_box"},
	      {name: "Artificial Lighting: Poor", type: "check_box"},
	      {name: "Cleanliness", type: "check_box"},
	      {name: "Congested", type: "check_box"},
	      {name: "HAZMAT/Toxic Substances", type: "check_box"},
	      {name: "Inadequate Blast Protection", type: "check_box"},
	      {name: "Not Adequate", type: "check_box"},
	      {name: "Power Sources", type: "check_box"},
	      {name: "Ramp Markings", type: "check_box"},
	      {name: "Ventilation", type: "check_box"},
	      {name: "Other Facilities", type: "text_field"},
	    ],
	    "Interface Issues" => [
	      {name: "Inadequate", type: "check_box"},
	      {name: "Ineffective", type: "check_box"},
	      {name: "Non Existent", type: "check_box"},
	      {name: "Not Documented", type: "check_box"},
	      {name: "Not Followed", type: "check_box"},
	      {name: "Other", type: "text_field"},
	    ],
	    "Leadership/Supervision Factors" => [
	      {name: "Leadership/Supervision Factors", type: "check_box"},
	      {name: "Amount of Supervision", type: "check_box"},
	      {name: "Delegation/Assignment of Tasks", type: "check_box"},
	      {name: "Does not Assure that Approved Process/Procedure is Followed", type: "check_box"},
	      {name: "Lack of Leadership/Supervision", type: "check_box"},
	      {name: "Planning/Organization of Tasks", type: "check_box"},
	      {name: "Prioritization of Work", type: "check_box"},
	      {name: "Unrealistic Attitude/Expectations", type: "check_box"},
	      {name: "Other Leadership/Supervision Factors", type: "text_field"},
	    ],
	    "Narrative" => [
	      {name: "Narrative", type: "text_area"},
	    ],
	    "Non-Compliance with CFRs, Policies/Procedures" => [
	      {name: "Non-Compliance with CFRs, Policies/Procedures", type: "check_box"},
	      {name: "Aircraft System SOPs", type: "check_box"},
	      {name: "Airworthiness Directive", type: "check_box"},
	      {name: "CFR Violation Part No", type: "text_field"},
	      {name: "CFRs", type: "check_box"},
	      {name: "Cabin Procedures", type: "check_box"},
	      {name: "Carry on Baggage Limit", type: "check_box"},
	      {name: "Checklist/Flows SOP Non-Compliance", type: "check_box"},
	      {name: "Company Policy SOP Non-Compliance", type: "check_box"},
	      {name: "Did Not Initialize Cabin Phone", type: "check_box"},
	      {name: "Errors/Violations by Others", type: "check_box"},
	      {name: "Exit Row/Moving Passenger Post Brief", type: "check_box"},
	      {name: "Failure to Qualify", type: "select", options: ["Ineligible Lap Child Allowed","Jump Seat/JACS","Exit Row Seating"]},
	      {name: "Flight/Duty Time Violation", type: "check_box"},
	      {name: "HAZMAT Violation", type: "check_box"},
	      {name: "Incorrect/Missing Manual Information", type: "check_box"},
	      {name: "Infant Edit Not Completed", type: "check_box"},
	      {name: "Non-Compliance-Clearance", type: "check_box"},
	      {name: "Non-Compliance-Service Advisory", type: "check_box"},
	      {name: "Preflight Check", type: "check_box"},
	      {name: "Problem Enforcing CFRs", type: "check_box"},
	      {name: "Published Procedure", type: "check_box"},
	      {name: "Reduced Safety Standards", type: "check_box"},
	      {name: "Reference", type: "text_field"},
	      {name: "Regulatory Fine", type: "check_box"},
	      {name: "Regulatory Violation", type: "check_box"},
	      {name: "Required Legal Separation", type: "check_box"},
	      {name: "Scheduling Rules", type: "check_box"},
	      {name: "Smoking Ban Violation", type: "check_box"},
	      {name: "Speed", type: "check_box"},
	      {name: "Sterile Cockpit Violation", type: "check_box"},
	      {name: "TSRs", type: "check_box"},
	      {name: "Unaccompanied Minor", type: "check_box"},
	      {name: "Weather Minimums", type: "check_box"},
	      {name: "Other Cabin Non Compliance", type: "text_field"},
	      {name: "Other Non-Compliance with CFRs, Policies/Procedures", type: "text_field"},
	    ],
	    "Organization Factors" => [
	      {name: "Organizational Factors", type: "check_box"},
	      {name: "Airline's Safety Culture", type: "check_box"},
	      {name: "Company Policies", type: "check_box"},
	      {name: "Corporate Change/Restructuring", type: "check_box"},
	      {name: "Crew Selection", type: "check_box"},
	      {name: "Employee Staffing", type: "check_box"},
	      {name: "Failure to Follow Airport Authority Guidance", type: "check_box"},
	      {name: "Failure to Follow Ground Guidance", type: "check_box"},
	      {name: "Flight Safety Standardization", type: "check_box"},
	      {name: "Improper Record Keeping Procedures", type: "check_box"},
	      {name: "Inadequate Flight Management", type: "check_box"},
	      {name: "Inadequate Ground Management", type: "check_box"},
	      {name: "Inadequate Training", type: "check_box"},
	      {name: "Labor Agreement", type: "check_box"},
	      {name: "Lack of Accountability", type: "check_box"},
	      {name: "Lack of Teamwork", type: "check_box"},
	      {name: "Mismanagement of Assets", type: "check_box"},
	      {name: "Not Enough Resources", type: "check_box"},
	      {name: "Not Enough Staff", type: "check_box"},
	      {name: "On Time Pressure", type: "check_box"},
	      {name: "Quality of Support from Airport Organizations", type: "check_box"},
	      {name: "Quality of Support from Airport Vendors", type: "check_box"},
	      {name: "Quality of Support from Management", type: "check_box"},
	      {name: "Reduced Safety Standards", type: "check_box"},
	      {name: "Rest/Duty/Flight Time", type: "check_box"},
	      {name: "Work Group Normal Practice (Norm)", type: "check_box"},
	      {name: "Work Process/Procedure", type: "check_box"},
	      {name: "Work Process/Procedure not Documented", type: "check_box"},
	      {name: "Work Process/Procedure not Followed", type: "check_box"},
	      {name: "Other Organizational Factors", type: "text_field"},
	    ],
	    "Policy Issues" => [
	      {name: "Conflicting", type: "check_box"},
	      {name: "Inadequate", type: "check_box"},
	      {name: "Ineffective", type: "check_box"},
	      {name: "Non Existent", type: "check_box"},
	      {name: "Not Documented", type: "check_box"},
	      {name: "Not Followed", type: "check_box"},
	      {name: "Other", type: "text_field"},
	    ],
	    "Potential Risk" => [
	      {name: "Aircraft Damage", type: "check_box"},
	      {name: "Equipment/Facility Damage", type: "check_box"},
	      {name: "Health/Chemical Hazard", type: "check_box"},
	      {name: "Injury", type: "check_box"},
	      {name: "Potential Aircraft Damage", type: "check_box"},
	      {name: "Potential Equipment/Facility Damage", type: "check_box"},
	      {name: "Potential Health/Chemical Hazard", type: "check_box"},
	      {name: "Potential Injury", type: "check_box"},
	      {name: "Potential Passenger", type: "check_box"},
	      {name: "Other Potential Risk", type: "text_field"},
	    ],
	    "Procedure Issues" => [
	      {name: "Conflicting", type: "check_box"},
	      {name: "Inadequate", type: "check_box"},
	      {name: "Ineffective", type: "check_box"},
	      {name: "Non Existent", type: "check_box"},
	      {name: "Not Documented", type: "check_box"},
	      {name: "Not Followed", type: "check_box"},
	      {name: "Other", type: "text_field"},
	    ],
	    "Process Measurement Issues" => [
	      {name: "Inadequate", type: "check_box"},
	      {name: "Ineffective", type: "check_box"},
	      {name: "Non Existent", type: "check_box"},
	      {name: "Not Documented", type: "check_box"},
	      {name: "Not Followed", type: "check_box"},
	      {name: "Other", type: "text_field"},
	    ],
	    "Responsibility Issues" => [
	      {name: "Conflicting", type: "check_box"},
	      {name: "Inadequate", type: "check_box"},
	      {name: "Ineffective", type: "check_box"},
	      {name: "Non Existent", type: "check_box"},
	      {name: "Not Documented", type: "check_box"},
	      {name: "Other", type: "text_field"},
	    ],
	    "SMS Communication and Awareness" => [
	      {name: "External Outputs of SMS", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Internal Outputs of SMS", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	    ],
	    "SMS Competencies and Training" => [
	      {name: "Personnel Expectiaions", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Training", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	    ],
	    "SMS Continual Improvement" => [
	      {name: "Communicate Lessons Learned", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Safety Lessons Learned", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	    ],
	    "SMS Gap Analysis" => [
	      {name: "Implementation Level", type: "select", options: ["Not Performed","Planned","Documented","Implemented","Demonstrated","Not Applicable"]},
	    ],
	    "SMS Gap Assessment-Rating" => [
	      {name: "Assessment Rating - Cabin", type: "select", options: ["not performed","planned","documented","implemented","demonstrated"]},
	      {name: "Assessment Rating - Cargo", type: "select", options: ["not performed","planned","documented","implemented","demonstrated"]},
	      {name: "Assessment Rating - Dispatch", type: "select", options: ["not performed","planned","documented","implemented","demonstrated"]},
	      {name: "Assessment Rating - Flight Operations", type: "select", options: ["not performed","planned","documented","implemented","demonstrated"]},
	      {name: "Assessment Rating - Ground", type: "select", options: ["not performed","planned","documented","implemented","demonstrated"]},
	      {name: "Assessment Rating - Maintenance", type: "select", options: ["not performed","planned","documented","implemented","demonstrated"]},
	      {name: "Assessment Rating - Overall Organization", type: "select", options: ["not performed","planned","documented","implemented","demonstrated"]},
	      {name: "Assessment Rating - Training", type: "select", options: ["not performed","planned","documented","implemented","demonstrated"]},
	    ],
	    "SMS Gap Narrative" => [
	      {name: "Cabin", type: "text_area"},
	      {name: "Cargo", type: "text_area"},
	      {name: "Dispatch", type: "text_area"},
	      {name: "Flight Operations", type: "text_area"},
	      {name: "Ground", type: "text_area"},
	      {name: "Maintenance", type: "text_area"},
	      {name: "Overall Organization", type: "text_area"},
	      {name: "Training", type: "text_area"},
	    ],
	    "SMS Hazard Identification and Analysis" => [
	      {name: "Identify Hazards", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "System and Task Analysis", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	    ],
	    "SMS Management and Change" => [
	      {name: "Change to Existing Design", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Modified Operation/Procedure", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "New Operation/Procedure", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "New System Design", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	    ],
	    "SMS Risk Assessment and Control" => [
	      {name: "Assess Safety Risk", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Control/Mitigate Safety Risk", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	    ],
	    "SMS Safety Performance Monitoring and Measurement" => [
	      {name: "Analysis of Data", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Continuous Monitoring", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Employee Reporting and Feedback System", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "External Audituing of the SMS", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Internal Audits by Operational Departments", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Internal Evaluation", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Investigation", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Management Review", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Preventative and Corrective Action", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "System Assessment", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	    ],
	    "SMS Safety Policies and Objectives" => [
	      {name: "Documentation and Records", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Emergency Preparedness and Response", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Management Commitment and Safety Accountabilities", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	      {name: "Safety Policy", type: "select", options: ["Inadequate","ineffective","Non-Existent","Not Documented","Not Followed"]},
	    ],
	    "Station Operation Issues" => [
	      {name: "Station Operation Issues", type: "check_box"},
	      {name: "Access Panel Left Open", type: "check_box"},
	      {name: "Air Start", type: "check_box"},
	      {name: "Crew Hotel/Transportation", type: "check_box"},
	      {name: "De-Icing", type: "check_box"},
	      {name: "HAZMAT", type: "check_box"},
	      {name: "Procedures", type: "check_box"},
	      {name: "Remote Dispatch", type: "check_box"},
	      {name: "Weather Resources", type: "check_box"},
	      {name: "Other Station Operation Issues", type: "text_field"},
	    ],
	    "Technical Data Error" => [
	      {name: "Technical Data Error", type: "check_box"},
	      {name: "Improper MEL/Deferral", type: "check_box"},
	      {name: "Manuals", type: "check_box"},
	      {name: "Reference Material", type: "check_box"},
	      {name: "Work Cards", type: "check_box"},
	      {name: "Other Technical Data", type: "text_field"},
	    ],
	    "Technical Knowledge/Skills" => [
	      {name: "Technical Knowledge/Skills/Training", type: "check_box"},
	      {name: "Aircraft Configuration Knowledge", type: "check_box"},
	      {name: "Computing Skills", type: "check_box"},
	      {name: "English Language Proficiency", type: "check_box"},
	      {name: "Inadequate Aircraft System Knowledge", type: "check_box"},
	      {name: "Inadequate Airline Process Knowledge", type: "check_box"},
	      {name: "Inadequate Skills", type: "check_box"},
	      {name: "Inadequate Task Experience", type: "check_box"},
	      {name: "Inadequate Task Knowledge", type: "check_box"},
	      {name: "Inadequate Task Planning", type: "check_box"},
	      {name: "Teamwork Skills", type: "check_box"},
	      {name: "Training Issues", type: "select", options: ["Incorrect","Lack of","No","Other","Yes"]},
	      {name: "Training Situation", type: "select", options: ["Instructing","Other","Receiving Training"]},
	      {name: "Other Technical Knowledge/Skills/Training", type: "text_field"},
	    ],
	    "Training: Customer Service Representatives" => [
	      {name: "Customer Service Representatives Training", type: "check_box"},
	      {name: "Documentation", type: "check_box"},
	      {name: "Passenger Carry Ons", type: "check_box"},
	      {name: "Policies/Procedures", type: "check_box"},
	      {name: "Security", type: "check_box"},
	      {name: "Special Handling Passengers", type: "check_box"},
	      {name: "Other Customer Service Representatives Training", type: "text_field"},
	    ],
	    "Training: Dispatchers" => [
	      {name: "Dispatcher Training", type: "check_box"},
	      {name: "Cockpit Jump Seat Observation", type: "check_box"},
	      {name: "Communications", type: "check_box"},
	      {name: "DRM Training", type: "check_box"},
	      {name: "Decisionmaking", type: "check_box"},
	      {name: "Deferred Items-MEL/CDL", type: "check_box"},
	      {name: "Field Conditions", type: "check_box"},
	      {name: "Flight Planning-Initial", type: "check_box"},
	      {name: "Flight Releases", type: "check_box"},
	      {name: "Initial", type: "check_box"},
	      {name: "NOTAMs", type: "check_box"},
	      {name: "Operational Control", type: "check_box"},
	      {name: "Policies/Procedures", type: "check_box"},
	      {name: "Recurrent", type: "check_box"},
	      {name: "Other Dispatcher Training", type: "text_field"},
	    ],
	    "Training: Flight Attendants" => [
	      {name: "Flight Attendants Training", type: "check_box"},
	      {name: "Cabin Maintenance Log", type: "check_box"},
	      {name: "Computer Based Training", type: "check_box"},
	      {name: "Drills", type: "check_box"},
	      {name: "Emergency Equipment", type: "check_box"},
	      {name: "Initial", type: "check_box"},
	      {name: "Life Support", type: "check_box"},
	      {name: "Overwater", type: "check_box"},
	      {name: "Policies/Procedures", type: "check_box"},
	      {name: "Recurrent", type: "check_box"},
	      {name: "Reports", type: "check_box"},
	      {name: "Security", type: "check_box"},
	      {name: "Other Flight Attendants Training", type: "text_field"},
	    ],
	    "Training: Ground Service Technicians" => [
	      {name: "Ground Service Technicians Training", type: "check_box"},
	      {name: "HAZMAT", type: "check_box"},
	      {name: "Marshalling", type: "check_box"},
	      {name: "Policies/Procedures", type: "check_box"},
	      {name: "Pushback", type: "check_box"},
	      {name: "Safety Zone", type: "check_box"},
	      {name: "Security", type: "check_box"},
	      {name: "Other Ground Service Technicians Training", type: "text_field"},
	    ],
	    "Training: Maintenance Technicians" => [
	      {name: "Maintenance Technicians Training", type: "check_box"},
	      {name: "APU Operations", type: "check_box"},
	      {name: "Air Start", type: "check_box"},
	      {name: "Policies/Procedures", type: "check_box"},
	      {name: "Taxi/Tow Operations", type: "check_box"},
	      {name: "Other Maintenance Technicians Training", type: "text_field"},
	    ],
	    "Training: Organization" => [
	      {name: "Organization Training", type: "check_box"},
	      {name: "Publish Article", type: "check_box"},
	      {name: "Standardization", type: "check_box"},
	      {name: "Supplement", type: "check_box"},
	      {name: "Other Organization Training", type: "text_field"},
	    ],
	    "Training: Pilots" => [
	      {name: "CRM", type: "check_box"},
	      {name: "Computer Based Training", type: "check_box"},
	      {name: "Emergency Equipment", type: "check_box"},
	      {name: "Flight Deck Procedures", type: "check_box"},
	      {name: "General Operating Systems", type: "check_box"},
	      {name: "Home Study", type: "check_box"},
	      {name: "Initial Indoctrination/Awareness", type: "check_box"},
	      {name: "MEL", type: "check_box"},
	      {name: "Overwater", type: "check_box"},
	      {name: "Pilot Training", type: "check_box"},
	      {name: "Policies/Procedures", type: "check_box"},
	      {name: "Recurrent", type: "check_box"},
	      {name: "SPT", type: "check_box"},
	      {name: "Simulator PC", type: "check_box"},
	      {name: "Simulator PT", type: "check_box"},
	      {name: "Standardization", type: "check_box"},
	      {name: "Systems Airbus", type: "select", options: ["A300","A310","A319","A320","A321","A330","Other"]},
	      {name: "Systems Boeing", type: "select", options: ["B717","B727","B737-100/200","B737-300/400/500","B737-NG","B747","B757","B767","B777","Other"]},
	      {name: "Systems Embraer", type: "select", options: ["EMB-120","EMB-135","EMB-140","EMB-145","EMB-XRJ","Other"]},
	      {name: "Transition", type: "check_box"},
	      {name: "Upgrade", type: "check_box"},
	      {name: "Other Pilot Training", type: "text_field"},
	    ],
	    "Weight and Balance Event" => [
	      {name: "Weight and Balance", type: "check_box"},
	      {name: "Actual Center of Gravity", type: "text_field"},
	      {name: "Actual Load Did Not Match Inbound Load Message", type: "check_box"},
	      {name: "Actual Weight", type: "text_field"},
	      {name: "Aircraft Loaded Weight/CG Error", type: "check_box"},
	      {name: "Aircraft Loaded Weight/CG Error", type: "select", options: ["Incorrect Bag Count","Incorrect Freight Weight","Other"]},
	      {name: "CG Difference", type: "text_field"},
	      {name: "CG from Datum", type: "check_box"},
	      {name: "CG from Nose", type: "check_box"},
	      {name: "CLP Contacted", type: "check_box"},
	      {name: "Calculation Error", type: "check_box"},
	      {name: "Cargo", type: "select", options: ["Restrained","Other","Shifting"]},
	      {name: "Cargo Loading Error", type: "check_box"},
	      {name: "Cargo Shift", type: "check_box"},
	      {name: "Cargo/Bag Documentation Error", type: "select", options: ["Undocumented Cargo Loaded","Documented Cargo Not Loaded","Undocumented Bag Loaded","Documented Bag Not Loaded","Items Not in Documented PIT","Other Count/Weight Error"]},
	      {name: "Center of Gravity", type: "check_box"},
	      {name: "Center of Gravity Error Type", type: "select", options: ["Cargo/Bags in Wrong Location","Igloos/Cargo Containers in Wrong Location"]},
	      {name: "Exceeded CG limitations", type: "check_box"},
	      {name: "Exceeded PIT/ULD limitations", type: "check_box"},
	      {name: "Exceeded running load restrictions", type: "check_box"},
	      {name: "Incorrect Planning Tool Used", type: "check_box"},
	      {name: "Input Error", type: "check_box"},
	      {name: "Items not in Documented Pit", type: "check_box"},
	      {name: "Load Verification Error", type: "check_box"},
	      {name: "MTOW Exceeded", type: "check_box"},
	      {name: "Maximum Landing Weight (lbs)", type: "text_field"},
	      {name: "Maximum Takeoff Weight (lbs)", type: "text_field"},
	      {name: "Maximum Taxi Weight (lbs)", type: "text_field"},
	      {name: "Maximum Zero Fuel Weight (lbs)", type: "text_field"},
	      {name: "Over Max Zero Fuel Weight", type: "check_box"},
	      {name: "Over Release Weight", type: "check_box"},
	      {name: "Overweight Takeoff", type: "check_box"},
	      {name: "Overweight Taxi", type: "check_box"},
	      {name: "Overweight for Ground Surface Limits", type: "check_box"},
	      {name: "Passenger Loading/Count Error", type: "check_box"},
	      {name: "Passenger Loading/Count Error Type", type: "select", options: ["Incorrect Count","Zone Distribution Error","Jump Seat Error"]},
	      {name: "Payload>10,000 Kgs", type: "check_box"},
	      {name: "Reported Center of Gravity", type: "text_field"},
	      {name: "Reported Weight", type: "text_field"},
	      {name: "Reported ZFW", type: "check_box"},
	      {name: "Shelf Weight Exceedence", type: "check_box"},
	      {name: "Center of Gravity Location at Time of Accident/Incident in Inches", type: "text_field"},
	      {name: "Percent Mean Aerodynamic Cord (%MAC)", type: "text_field"},
	      {name: "Actual ZFW", type: "text_field"},
	      {name: "Other Weight and Balance Event", type: "text_field"},
	      {name: "Reported ZFW", type: "text_field"},
	      {name: "Weight Difference", type: "text_field"},
	    ],
	  }).sort.to_h
	end


end
